#!/usr/bin/env python3
"""
Bring each Wind mee theme to at least 150 words. No duplicates (case-insensitive per theme).
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
WINDMEE_PATH = ROOT / "apps" / "web" / "public" / "content" / "windmee.json"
MIN_PER_THEME = 150

# Additional words per theme to reach 150+. Format: (nl, en, article)
# Only words not already in the theme. Script skips duplicates.
EXTRA_VOCAB = {
    1: [  # Wonen - 95 -> 150, need 55
        ("raam", "window", "het"),
        ("vloer", "floor", "de"),
        ("plafond", "ceiling", "het"),
        ("muur", "wall", "de"),
        ("licht", "light", "het"),
        ("stopcontact", "socket", "het"),
        ("schakelaar", "switch", "de"),
        ("radiator", "radiator", "de"),
        ("afvoer", "drain", "de"),
        ("douchekop", "shower head", "de"),
        ("handzeep", "hand soap", "de"),
        ("wastafelkastje", "bathroom cabinet", "het"),
        ("badmat", "bath mat", "de"),
        ("handdoekrek", "towel rack", "het"),
        ("wastafel", "sink", "de"),
        ("afvalbak", "waste bin", "de"),
        ("plant", "plant", "de"),
        ("boekenkast", "bookshelf", "de"),
        ("tv-meubel", "TV stand", "het"),
        ("bankstel", "sofa set", "het"),
        ("eetkamer", "dining room", "de"),
        ("berging", "storage", "de"),
        ("wasplaats", "utility room", "de"),
        ("droogrek", "drying rack", "het"),
        ("waslijn", "clothes line", "de"),
        ("stofzuiger", "vacuum cleaner", "de"),
        ("emmer", "bucket", "de"),
        ("dweil", "mop", "de"),
        ("bezem", "broom", "de"),
        ("schoonmaken", "to clean", None),
        ("opruimen", "to tidy", None),
        ("stof afnemen", "to dust", None),
        ("ramen zemen", "to clean windows", None),
        ("vuilnis", "garbage", "het"),
        ("recyclen", "to recycle", None),
        ("composteren", "to compost", None),
        ("tuinmeubel", "garden furniture", "het"),
        ("parasol", "parasol", "de"),
        ("ligstoel", "sun lounger", "de"),
        ("barbecue", "barbecue", "de"),
        ("schutting", "fence", "de"),
        ("hek", "gate", "het"),
        ("oprit", "driveway", "de"),
        ("voordeur", "front door", "de"),
        ("achterdeur", "back door", "de"),
        ("deurbel", "doorbell", "de"),
        ("sleutel", "key", "de"),
        ("slot", "lock", "het"),
        ("intercom", "intercom", "de"),
        ("deurmat", "doormat", "de"),
        ("kapstok", "coat rack", "de"),
        ("schoenenkast", "shoe cabinet", "de"),
        ("gang", "hallway", "de"),
        ("overloop", "landing", "de"),
        ("zolder", "attic", "de"),
        ("kelder", "cellar", "de"),
        ("traploper", "stair runner", "de"),
        ("vensterbank", "windowsill", "de"),
        ("gordijn", "curtain", "het"),
        ("lampenkap", "lampshade", "de"),
    ],
    2: [  # Sociale contacten - 66 -> 150, need 84
        ("contact", "contact", "het"),
        ("netwerk", "network", "het"),
        ("relatie", "relationship", "de"),
        ("vriendschap", "friendship", "de"),
        ("kennismaking", "introduction", "de"),
        ("ontmoeting", "meeting", "de"),
        ("afspraakje", "date", "het"),
        ("verjaardag", "birthday", "de"),
        ("jubileum", "anniversary", "het"),
        ("babyborrel", "baby shower", "de"),
        ("housewarming", "housewarming", "de"),
        ("reünie", "reunion", "de"),
        ("borrel", "drinks", "de"),
        ("etentje", "dinner", "het"),
        ("lunchafspraak", "lunch date", "de"),
        ("koffiedate", "coffee date", "de"),
        ("videobellen", "to video call", None),
        ("appen", "to message", None),
        ("reageren", "to respond", None),
        ("liken", "to like", None),
        ("delen", "to share", None),
        ("posten", "to post", None),
        ("chatten", "to chat", None),
        ("mailen", "to email", None),
        ("een bericht sturen", "to send a message", None),
        ("oproepen", "to call", None),
        ("bereikbaar", "reachable", None),
        ("onbereikbaar", "unreachable", None),
        ("druk", "busy", None),
        ("beschikbaar", "available", None),
        ("vrij", "free", None),
        ("gepland", "planned", None),
        ("spontaan", "spontaneous", None),
        ("formeel", "formal", None),
        ("hartelijk", "warm", None),
        ("vriendelijk", "friendly", None),
        ("attent", "thoughtful", None),
        ("gastvrij", "hospitable", None),
        ("gezelschap", "company", "het"),
        ("samen zijn", "to be together", None),
        ("afspreken met", "to meet with", None),
        ("langskomen", "to drop by", None),
        ("uitnodigen voor", "to invite for", None),
        ("bedanken", "to thank", None),
        ("feliciteren", "to congratulate", None),
        ("condoleren", "to condole", None),
        ("troosten", "to comfort", None),
        ("aanmoedigen", "to encourage", None),
        ("liefde", "love", "de"),
        ("vertrouwen", "trust", "het"),
        ("verbondenheid", "connection", "de"),
        ("solidariteit", "solidarity", "de"),
        ("empatisch", "empathetic", None),
        ("begripvol", "understanding", None),
        ("respectvol", "respectful", None),
        ("open", "open", None),
        ("eerlijk", "honest", None),
        ("oprecht", "sincere", None),
        ("warm", "warm", None),
        ("koel", "cool", None),
        ("afstandelijk", "distant", None),
        ("geïrriteerd", "irritated", None),
        ("boos", "angry", None),
        ("blijdschap", "joy", "de"),
        ("teleurstelling", "disappointment", "de"),
        ("verwachting", "expectation", "de"),
        ("spanning", "tension", "de"),
        ("ontspanning", "relaxation", "de"),
        ("gezelligheid", "coziness", "de"),
        ("sfeer", "atmosphere", "de"),
        ("moment", "moment", "het"),
        ("herinnering", "memory", "de"),
        ("foto", "photo", "de"),
        ("selfie", "selfie", "de"),
        ("groepsfoto", "group photo", "de"),
        ("verjaardagskaart", "birthday card", "de"),
        ("condoleancekaart", "condolence card", "de"),
        ("bericht", "message", "het"),
        ("gesprek", "conversation", "het"),
        ("dialoog", "dialogue", "de"),
        ("small talk", "small talk", "de"),
        ("onderwerp", "topic", "het"),
        ("gespreksstof", "conversation topic", "de"),
        ("kennismaken", "to get to know", None),
        ("weerzien", "reunion", "het"),
        ("afscheid", "farewell", "het"),
        ("tot ziens", "goodbye", None),
        ("tot later", "see you later", None),
        ("praatje", "chat", "het"),
        ("afspraakje", "date", "het"),
        ("kennismakingsgesprek", "introductory chat", "het"),
        ("verjaardagsvisite", "birthday visit", "de"),
    ],
    3: [  # Onderwijs - 80 -> 150, need 70
        ("peuterspeelzaal", "playgroup", "de"),
        ("kleuterschool", "kindergarten", "de"),
        ("groep", "group", "de"),
        ("leerjaar", "school year", "het"),
        ("semester", "semester", "het"),
        ("trimester", "trimester", "het"),
        ("vakantie", "holiday", "de"),
        ("herfstvakantie", "autumn break", "de"),
        ("kerstvakantie", "Christmas break", "de"),
        ("voorjaarsvakantie", "spring break", "de"),
        ("zomervakantie", "summer holiday", "de"),
        ("studiedag", "study day", "de"),
        ("vrije dag", "day off", "de"),
        ("lesuur", "lesson", "het"),
        ("pauze", "break", "de"),
        ("speelkwartier", "playtime", "het"),
        ("schoolbel", "school bell", "de"),
        ("schoolplein", "schoolyard", "het"),
        ("klaslokaal", "classroom", "het"),
        ("directeur", "headteacher", "de"),
        ("conciërge", "caretaker", "de"),
        ("secretariaat", "office", "het"),
        ("kantine", "canteen", "de"),
        ("gymzaal", "gym", "de"),
        ("laboratorium", "laboratory", "het"),
        ("computerlokaal", "computer room", "het"),
        ("mediatheek", "media library", "de"),
        ("studieplek", "study space", "de"),
        ("werkstuk", "assignment", "het"),
        ("opdracht", "assignment", "de"),
        ("samenwerking", "collaboration", "de"),
        ("groepswerk", "group work", "het"),
        ("individueel", "individual", None),
        ("mondeling", "oral", None),
        ("schriftelijk", "written", None),
        ("multiple choice", "multiple choice", None),
        ("open vraag", "open question", "de"),
        ("tentamen", "exam", "het"),
        ("herkansing", "retake", "de"),
        ("tussentijdse toets", "midterm", "de"),
        ("eindcijfer", "final grade", "het"),
        ("gemiddelde", "average", "het"),
        ("slagen", "to pass", None),
        ("zakken", "to fail", None),
        ("cum laude", "with honours", None),
        ("propedeuse", "first year", "de"),
        ("bachelor", "bachelor", "de"),
        ("master", "master", "de"),
        ("doctoraal", "doctoral", None),
        ("promotie", "PhD", "de"),
        ("wetenschapper", "scientist", "de"),
        ("onderzoek", "research", "het"),
        ("scriptie", "thesis", "de"),
        ("dissertatie", "dissertation", "de"),
        ("begeleider", "supervisor", "de"),
        ("examinator", "examiner", "de"),
        ("commissie", "committee", "de"),
        ("studiepunten", "credits", "de"),
        ("ects", "ECTS", "de"),
        ("inschrijven", "to enroll", None),
        ("uitschrijven", "to deregister", None),
        ("collegegeld", "tuition fee", "het"),
        ("studiefinanciering", "student finance", "de"),
        ("studielening", "student loan", "de"),
        ("studentenov", "student travel", "de"),
        ("studentenvereniging", "student association", "de"),
        ("sorority", "sorority", "de"),
        ("studentenhuis", "student house", "het"),
        ("kamernet", "Kamernet", "het"),
        ("studiebeurs", "study grant", "de"),
        ("honours", "honours", "het"),
        ("minor", "minor", "de"),
        ("major", "major", "de"),
        ("keuzevak", "elective", "het"),
        ("verplicht vak", "required course", "het"),
        ("tentamenweek", "exam week", "de"),
        ("blok", "block", "het"),
    ],
    4: [  # Werk zoeken - 63 -> 150, need 87
        ("arbeidsmarkt", "job market", "de"),
        ("vacaturebank", "job board", "de"),
        ("indeed", "Indeed", "de"),
        ("monsterboard", "Monsterboard", "het"),
        ("loopbaan", "career", "de"),
        ("carrièrestap", "career step", "de"),
        ("carrièreswitch", "career change", "de"),
        ("doorgroeimogelijkheid", "growth opportunity", "de"),
        ("doorgroei", "advancement", "de"),
        ("promotie", "promotion", "de"),
        ("salarisverhoging", "salary increase", "de"),
        ("bonus", "bonus", "de"),
        ("commissie", "commission", "de"),
        ("reiskostenvergoeding", "travel allowance", "de"),
        ("onkostenvergoeding", "expense allowance", "de"),
        ("pensioenopbouw", "pension build-up", "de"),
        ("vakantiedagen", "holiday days", "de"),
        ("adv-dagen", "days in lieu", "de"),
        ("ziektedagen", "sick days", "de"),
        ("ouderverlof", "parental leave", "het"),
        ("zwangerschapsverlof", "maternity leave", "het"),
        ("papaverlof", "paternity leave", "het"),
        ("sabbatical", "sabbatical", "de"),
        ("detachering", "secondment", "de"),
        ("zzp", "self-employed", "de"),
        ("freelancer", "freelancer", "de"),
        ("opdrachtgever", "client", "de"),
        ("opdrachtnemer", "contractor", "de"),
        ("uitzendbureau", "temp agency", "het"),
        ("uitzendkracht", "temp worker", "de"),
        ("vast contract", "permanent contract", "het"),
        ("tijdelijk contract", "temporary contract", "het"),
        ("nulurencontract", "zero-hours contract", "het"),
        ("stageplek", "internship place", "de"),
        ("meeloopdag", "shadow day", "de"),
        ("proefdag", "trial day", "de"),
        ("assessment", "assessment", "het"),
        ("assessmentdag", "assessment day", "de"),
        ("casus", "case", "de"),
        ("rollenspel", "role play", "het"),
        ("competentiegericht", "competency-based", None),
        ("gedragsgericht", "behavioral", None),
        ("sterke punten", "strengths", "de"),
        ("zwakke punten", "weaknesses", "de"),
        ("ontwikkelpunten", "development points", "de"),
        ("leiderschap", "leadership", "het"),
        ("communicatie", "communication", "de"),
        ("probleemoplossend", "problem-solving", None),
        ("analytisch", "analytical", None),
        ("resultaatgericht", "result-oriented", None),
        ("klantgericht", "customer-oriented", None),
        ("teamspeler", "team player", "de"),
        ("zelfstandigheid", "independence", "de"),
        ("flexibiliteit", "flexibility", "de"),
        ("stressbestendigheid", "stress resistance", "de"),
        ("multitasken", "to multitask", None),
        ("prioriteren", "to prioritize", None),
        ("deadlines halen", "to meet deadlines", None),
        ("kwaliteit leveren", "to deliver quality", None),
        ("feedback geven", "to give feedback", None),
        ("feedback ontvangen", "to receive feedback", None),
        ("evaluatie", "evaluation", "de"),
        ("functioneringsgesprek", "performance review", "het"),
        ("beoordelingsgesprek", "appraisal", "het"),
        ("ontslag", "dismissal", "het"),
        ("ontslag nemen", "to resign", None),
        ("ontslagen worden", "to be fired", None),
        ("opzegtermijn", "notice period", "de"),
        ("vrijwillig", "voluntary", None),
        ("gedwongen", "forced", None),
        ("reorganisatie", "reorganization", "de"),
        ("fusie", "merge", "de"),
        ("overname", "takeover", "de"),
        ("faillissement", "bankruptcy", "het"),
        ("vacature", "vacancy", "de"),
        ("functie-eisen", "job requirements", "de"),
        ("profiel", "profile", "het"),
        ("cv", "CV", "het"),
        ("sollicitatiebrief", "cover letter", "de"),
        ("aanbevelingsbrief", "reference letter", "de"),
        ("netwerken", "to network", None),
        ("informatiengesprek", "informational interview", "het"),
        ("sollicitatiegesprek", "job interview", "het"),
        ("assessment center", "assessment centre", "het"),
        ("sollicitatieprocedure", "application procedure", "de"),
        ("vacatureadvertentie", "job advertisement", "de"),
        ("sollicitatiedeadline", "application deadline", "de"),
        ("aanstellingsgesprek", "offer meeting", "het"),
        ("contractvoorstel", "contract proposal", "het"),
        ("onderhandelingspositie", "negotiating position", "de"),
        ("aanbod", "offer", "het"),
        ("arbeidsvoorwaarden", "terms of employment", "de"),
        ("startdatum", "start date", "de"),
        ("vacaturebank", "job board", "de"),
        ("sollicitatieprocedure", "application procedure", "de"),
        ("functieomschrijving", "job description", "de"),
        ("salarisindicatie", "salary indication", "de"),
    ],
    5: [  # Een dag op het werk - 62 -> 150, need 88
        ("werkdag", "workday", "de"),
        ("kantoordag", "office day", "de"),
        ("thuiswerkdag", "work from home day", "de"),
        ("starttijd", "start time", "de"),
        ("eindtijd", "end time", "de"),
        ("pauzetijd", "break time", "de"),
        ("lunchpauze", "lunch break", "de"),
        ("koffiepauze", "coffee break", "de"),
        ("rooster", "schedule", "het"),
        ("dienstrooster", "shift schedule", "het"),
        ("wisseldienst", "rotating shift", "de"),
        ("vroege dienst", "early shift", "de"),
        ("late dienst", "late shift", "de"),
        ("nachtdienst", "night shift", "de"),
        ("weekenddienst", "weekend shift", "de"),
        ("feestdagen", "public holidays", "de"),
        ("kantoorruimte", "office space", "de"),
        ("werkplek", "workstation", "de"),
        ("bureau", "desk", "het"),
        ("stoel", "chair", "de"),
        ("beeldscherm", "screen", "het"),
        ("toetsenbord", "keyboard", "het"),
        ("muis", "mouse", "de"),
        ("headset", "headset", "de"),
        ("webcam", "webcam", "de"),
        ("telefoon", "phone", "de"),
        ("intercom", "intercom", "de"),
        ("printer", "printer", "de"),
        ("scanner", "scanner", "de"),
        ("archiefkast", "filing cabinet", "de"),
        ("whiteboard", "whiteboard", "het"),
        ("flipover", "flip chart", "de"),
        ("beamer", "projector", "de"),
        ("vergaderruimte", "meeting room", "de"),
        ("conferentiezaal", "conference room", "de"),
        ("breakout room", "breakout room", "de"),
        ("kantine", "canteen", "de"),
        ("koffiehoek", "coffee corner", "de"),
        ("rookruimte", "smoking area", "de"),
        ("parkeerplaats", "parking", "de"),
        ("fietsenstalling", "bike shed", "de"),
        ("informatie", "information", "de"),
        ("documentatie", "documentation", "de"),
        ("handleiding", "manual", "de"),
        ("protocol", "protocol", "het"),
        ("procedure", "procedure", "de"),
        ("werkproces", "work process", "het"),
        ("workflow", "workflow", "de"),
        ("deadline", "deadline", "de"),
        ("prioriteit", "priority", "de"),
        ("urgent", "urgent", None),
        ("belangrijk", "important", None),
        ("routine", "routine", "de"),
        ("ad-hoc", "ad hoc", None),
        ("structureel", "structural", None),
        ("incident", "incident", "het"),
        ("crisis", "crisis", "de"),
        ("noodgeval", "emergency", "het"),
        ("back-up", "backup", "de"),
        ("vervanger", "replacement", "de"),
        ("waarneming", "acting", "de"),
        ("delegatie", "delegation", "de"),
        ("verantwoordelijkheid", "responsibility", "de"),
        ("bevoegdheid", "authority", "de"),
        ("hiërarchie", "hierarchy", "de"),
        ("leidinggevende", "manager", "de"),
        ("directeur", "director", "de"),
        ("ceo", "CEO", "de"),
        ("afdelingshoofd", "department head", "de"),
        ("teamleider", "team leader", "de"),
        ("projectleider", "project manager", "de"),
        ("stakeholder", "stakeholder", "de"),
        ("klant", "customer", "de"),
        ("leverancier", "supplier", "de"),
        ("partner", "partner", "de"),
        ("concurrent", "competitor", "de"),
        ("branche", "sector", "de"),
        ("markt", "market", "de"),
        ("bedrijf", "company", "het"),
        ("organisatie", "organization", "de"),
        ("vestiging", "branch", "de"),
        ("hoofdkantoor", "headquarters", "het"),
        ("werkoverleg", "work meeting", "het"),
        ("stand-up", "stand-up", "de"),
        ("retrospective", "retrospective", "de"),
        ("brainstorm", "brainstorm", "de"),
        ("idee", "idea", "het"),
        ("voorstel", "proposal", "het"),
        ("besluit", "decision", "het"),
        ("akkoord", "agreement", "het"),
        ("vergaderagenda", "meeting agenda", "de"),
        ("vergaderruimte reserveren", "to book meeting room", None),
        ("notities maken", "to take notes", None),
        ("actielijst", "action list", "de"),
        ("follow-up", "follow-up", "de"),
        ("werkoverleg", "work meeting", "het"),
        ("projectoverleg", "project meeting", "het"),
        ("kwartaaloverleg", "quarterly meeting", "het"),
        ("jaaroverzicht", "annual overview", "het"),
        ("werkplekinrichting", "workplace design", "de"),
        ("ergonomie", "ergonomics", "de"),
        ("bureausetup", "desk setup", "de"),
        ("thuiswerkplek", "home workspace", "de"),
        ("kantoorbenodigdheden", "office supplies", "de"),
        ("kantoorpand", "office building", "het"),
        ("werkdruk", "workload", "de"),
        ("kantoorcultuur", "office culture", "de"),
    ],
    6: [  # Officiële instanties - 54 -> 150, need 96
        ("overheid", "government", "de"),
        ("instantie", "agency", "de"),
        ("dienst", "department", "de"),
        ("kantoor", "office", "het"),
        ("balie", "counter", "de"),
        ("loket", "window", "het"),
        ("openingstijden", "opening hours", "de"),
        ("wachtlijst", "waiting list", "de"),
        ("wachtijd", "waiting time", "de"),
        ("afspraak", "appointment", "de"),
        ("walk-in", "walk-in", "de"),
        ("online", "online", None),
        ("digitaal", "digital", None),
        ("papier", "paper", "het"),
        ("origineel", "original", None),
        ("kopie", "copy", "de"),
        ("gelegaliseerd", "legalized", None),
        ("vertaald", "translated", None),
        ("gewettigd", "certified", None),
        ("notaris", "notary", "de"),
        ("ambassade", "embassy", "de"),
        ("consulaat", "consulate", "het"),
        ("visum", "visa", "het"),
        ("verblijfsvergunning", "residence permit", "de"),
        ("arbeidsvergunning", "work permit", "de"),
        ("gezinshereniging", "family reunification", "de"),
        ("asiel", "asylum", "het"),
        ("vluchteling", "refugee", "de"),
        ("statushouder", "status holder", "de"),
        ("inburgeringsplicht", "integration requirement", "de"),
        ("inburgeringscursus", "integration course", "de"),
        ("taalcursus", "language course", "de"),
        ("niveau", "level", "het"),
        ("examen", "exam", "het"),
        ("certificaat", "certificate", "het"),
        ("diploma", "diploma", "het"),
        ("rijvaardigheid", "driving ability", "de"),
        ("theorie", "theory", "de"),
        ("praktijk", "practice", "de"),
        ("rijschool", "driving school", "de"),
        ("examencentrum", "exam centre", "het"),
        ("cbr", "CBR", "het"),
        ("gezondheidsverklaring", "health declaration", "de"),
        ("gezichtsvermogen", "eyesight", "het"),
        ("bril", "glasses", "de"),
        ("contactlenzen", "contact lenses", "de"),
        ("adres", "address", "het"),
        ("postcode", "postcode", "de"),
        ("woonplaats", "place of residence", "de"),
        ("nationaliteit", "nationality", "de"),
        ("geboorteland", "country of birth", "het"),
        ("burgerschap", "citizenship", "het"),
        ("dubbele nationaliteit", "dual nationality", "de"),
        ("naturalisatie", "naturalization", "de"),
        ("optie", "option", "de"),
        ("eerste verblijfsvergunning", "first residence permit", "de"),
        ("verlenging", "extension", "de"),
        ("verblijfsrecht", "right of residence", "het"),
        ("arbeidsrecht", "right to work", "het"),
        ("studievoucher", "study voucher", "de"),
        ("inburgeringslening", "integration loan", "de"),
        ("lening", "loan", "de"),
        ("terugbetalen", "to repay", None),
        ("vrijstelling", "exemption", "de"),
        ("kwijtschelding", "waiver", "de"),
        ("aanvraag", "application", "de"),
        ("indienen", "to submit", None),
        ("bevestiging", "confirmation", "de"),
        ("afwijzing", "rejection", "de"),
        ("bezwaar", "objection", "het"),
        ("beroep", "appeal", "het"),
        ("rechter", "judge", "de"),
        ("rechtbank", "court", "de"),
        ("advocaat", "lawyer", "de"),
        ("juridisch", "legal", None),
        ("migrant", "migrant", "de"),
        ("immigrant", "immigrant", "de"),
        ("emigrant", "emigrant", "de"),
        ("expat", "expat", "de"),
        ("pasfoto", "passport photo", "de"),
        ("vingerafdruk", "fingerprint", "de"),
        ("biometrie", "biometrics", "de"),
        ("chipkaart", "chip card", "de"),
        ("digid-activeren", "to activate DigiD", None),
        ("mijn overheid", "MijnOverheid", "de"),
        ("belastingaangifte", "tax return", "de"),
        ("toeslagen", "allowances", "de"),
        ("kinderbijslag", "child benefit", "de"),
        ("huurtoeslag", "rent allowance", "de"),
        ("zorgtoeslag", "healthcare allowance", "de"),
        ("geboorteaangifte", "birth registration", "de"),
        ("gezagsverklaring", "authority declaration", "de"),
        ("gezag", "custody", "het"),
        ("huwelijksaangifte", "marriage registration", "de"),
        ("overlijdensaangifte", "death registration", "de"),
        ("naamsvermelding", "name mention", "de"),
        ("achternaam", "surname", "de"),
        ("voornaam", "first name", "de"),
        ("tussenvoegsel", "middle name", "het"),
        ("identiteitskaart", "identity card", "de"),
        ("rijbewijsnr", "driving licence number", "het"),
        ("paspoortnummer", "passport number", "het"),
        ("vervaldatum", "expiry date", "de"),
        ("geldigheidsduur", "validity period", "de"),
        ("aanvraagprocedure", "application procedure", "de"),
        ("geboorteaangifte doen", "to register birth", None),
        ("paspoortaanvraag", "passport application", "de"),
        ("rijbewijsaanvraag", "driving licence application", "de"),
        ("verblijfsdocument", "residence document", "het"),
        ("vreemdelingenpolitie", "immigration police", "de"),
        ("ind", "IND", "de"),
        ("naturalisatieceremonie", "naturalization ceremony", "de"),
        ("eed afleggen", "to take an oath", None),
        ("burgerschap verkrijgen", "to obtain citizenship", None),
    ],
    7: [  # Op reis door Nederland - 62 -> 150, need 88
        ("reizen", "to travel", None),
        ("treinreizen", "train travel", "het"),
        ("busreizen", "bus travel", "het"),
        ("vliegen", "to fly", None),
        ("varen", "to sail", None),
        ("fietsen", "to cycle", None),
        ("lopen", "to walk", None),
        ("rijden", "to drive", None),
        ("meerijden", "to ride along", None),
        ("lift", "lift", "de"),
        ("carpoolen", "to carpool", None),
        ("ov", "public transport", "het"),
        ("ns", "Dutch Railways", "de"),
        ("arriva", "Arriva", "de"),
        ("connexxion", "Connexxion", "de"),
        ("gvb", "GVB", "het"),
        ("ret", "RET", "de"),
        ("htm", "HTM", "de"),
        ("ov-chipkaart", "OV-chipkaart", "de"),
        ("anonieme ov-chipkaart", "anonymous card", "de"),
        ("persoonlijke ov-chipkaart", "personal card", "de"),
        ("saldo", "balance", "het"),
        ("opwaarderen", "to top up", None),
        ("inchecken", "to check in", None),
        ("uitchecken", "to check out", None),
        ("overstap", "transfer", "de"),
        ("overstaptijd", "transfer time", "de"),
        ("rechtstreeks", "direct", None),
        ("via", "via", None),
        ("vertrek", "departure", "het"),
        ("aankomst", "arrival", "de"),
        ("vertrektijd", "departure time", "de"),
        ("aankomsttijd", "arrival time", "de"),
        ("spoor", "track", "het"),
        ("perron", "platform", "het"),
        ("halte", "stop", "de"),
        ("eindhalte", "terminal", "de"),
        ("tussenstop", "stopover", "de"),
        ("vertraging", "delay", "de"),
        ("geen dienst", "no service", None),
        ("storing", "disruption", "de"),
        ("omleiding", "diversion", "de"),
        ("vervangend vervoer", "replacement transport", "het"),
        ("busvervangend vervoer", "replacement bus", "het"),
        ("fietsverhuur", "bike rental", "de"),
        ("ov-fiets", "OV bike", "de"),
        ("deelfiets", "shared bike", "de"),
        ("scooter", "scooter", "de"),
        ("taxi", "taxi", "de"),
        ("uber", "Uber", "de"),
        ("blablacar", "BlaBlaCar", "de"),
        ("rit", "ride", "de"),
        ("reis", "journey", "de"),
        ("reisduur", "travel time", "de"),
        ("afstand", "distance", "de"),
        ("kilometer", "kilometre", "de"),
        ("reisschema", "travel schedule", "het"),
        ("reisplanner", "journey planner", "de"),
        ("9292", "9292", "de"),
        ("google maps", "Google Maps", "de"),
        ("navigatie", "navigation", "de"),
        ("gps", "GPS", "de"),
        ("verkeer", "traffic", "het"),
        ("file", "traffic jam", "de"),
        ("drukte", "crowding", "de"),
        ("spits", "rush hour", "de"),
        ("spitsuur", "peak hour", "het"),
        ("druk", "busy", None),
        ("rustig", "quiet", None),
        ("comfortabel", "comfortable", None),
        ("vol", "full", None),
        ("leeg", "empty", None),
        ("schoon", "clean", None),
        ("vies", "dirty", None),
        ("toegankelijk", "accessible", None),
        ("rolstoeltoegankelijk", "wheelchair accessible", None),
        ("toegankelijkheid", "accessibility", "de"),
        ("reistijd", "travel time", "de"),
        ("vertrekhal", "departure hall", "de"),
        ("aankomsthal", "arrival hall", "de"),
        ("bagageband", "baggage carousel", "de"),
        ("incheckbalie", "check-in desk", "de"),
        ("boardingpas", "boarding pass", "de"),
        ("gate", "gate", "de"),
        ("vlucht", "flight", "de"),
        ("treinverbinding", "train connection", "de"),
        ("overstapstation", "interchange station", "het"),
        ("spoorweg", "railway", "de"),
        ("metro", "metro", "de"),
        ("lightrail", "light rail", "de"),
        ("sneltram", "rapid tram", "de"),
        ("waterbus", "water bus", "de"),
        ("rondvaart", "canal cruise", "de"),
        ("toerist", "tourist", "de"),
        ("reiziger", "traveller", "de"),
        ("forens", "commuter", "de"),
        ("fietsroute", "cycle route", "de"),
        ("wandelroute", "walking route", "de"),
        ("autosnelweg", "motorway", "de"),
        ("provinciale weg", "provincial road", "de"),
        ("rijksweg", "national road", "de"),
        ("brug", "bridge", "de"),
        ("tunnel", "tunnel", "de"),
        ("viaduct", "viaduct", "het"),
        ("treinreiziger", "train passenger", "de"),
        ("busreiziger", "bus passenger", "de"),
        ("fietser", "cyclist", "de"),
        ("voetganger", "pedestrian", "de"),
        ("automobilist", "motorist", "de"),
        ("reizigersinformatie", "travel information", "de"),
        ("vertrekschema", "departure schedule", "het"),
    ],
    8: [  # Geld - 56 -> 150, need 94
        ("financiën", "finances", "de"),
        ("geldzaken", "financial affairs", "de"),
        ("financieel", "financial", None),
        ("geldelijk", "monetary", None),
        ("bedrag", "amount", "het"),
        ("som", "sum", "de"),
        ("totaal", "total", "het"),
        ("subtotaal", "subtotal", "het"),
        ("korting", "discount", "de"),
        ("btw", "VAT", "de"),
        ("belasting", "tax", "de"),
        ("belastingaangifte", "tax return", "de"),
        ("belastingdienst", "tax office", "de"),
        ("aanslag", "assessment", "de"),
        ("teruggave", "refund", "de"),
        ("voorheffing", "withholding", "de"),
        ("loonheffing", "wage tax", "de"),
        ("premie", "premium", "de"),
        ("zorgpremie", "health premium", "de"),
        ("eigen risico", "excess", "het"),
        ("verzekeraar", "insurer", "de"),
        ("polis", "policy", "de"),
        ("polisvoorwaarden", "policy terms", "de"),
        ("dekking", "coverage", "de"),
        ("verzekerd", "insured", None),
        ("onverzekerd", "uninsured", None),
        ("aansprakelijk", "liable", None),
        ("aansprakelijkheidsverzekering", "liability insurance", "de"),
        ("rechtsbijstand", "legal aid", "de"),
        ("rechtsbijstandverzekering", "legal expenses insurance", "de"),
        ("reisverzekering", "travel insurance", "de"),
        ("annulering", "cancellation", "de"),
        ("annuleringsverzekering", "cancellation insurance", "de"),
        ("spaarpot", "piggy bank", "de"),
        ("spaargeld", "savings", "het"),
        ("spaardoel", "savings goal", "het"),
        ("budgetteren", "to budget", None),
        ("uitgaven bijhouden", "to track expenses", None),
        ("huishoudboekje", "household budget", "het"),
        ("excel", "Excel", "de"),
        ("app", "app", "de"),
        ("geld-app", "money app", "de"),
        ("ideal", "iDEAL", "de"),
        ("paypal", "PayPal", "de"),
        ("creditcard", "credit card", "de"),
        ("pinpas", "debit card", "de"),
        ("paspoort", "passport", "het"),
        ("pincode", "PIN code", "de"),
        ("geheim", "secret", "het"),
        ("fraude", "fraud", "de"),
        ("oplichting", "scam", "de"),
        ("phishing", "phishing", "de"),
        ("waarschuwing", "warning", "de"),
        ("voorzichtig", "careful", None),
        ("veilig", "safe", None),
        ("onveilig", "unsafe", None),
        ("encryptie", "encryption", "de"),
        ("tweefactorauthenticatie", "two-factor authentication", "de"),
        ("2fa", "2FA", "de"),
        ("lening", "loan", "de"),
        ("hypotheek", "mortgage", "de"),
        ("rente", "interest", "de"),
        ("rentepercentage", "interest rate", "het"),
        ("aflossing", "repayment", "de"),
        ("maandlasten", "monthly payments", "de"),
        ("schuld", "debt", "de"),
        ("schulden", "debts", "de"),
        ("schuldsanering", "debt restructuring", "de"),
        ("betalingsregeling", "payment plan", "de"),
        ("incassobureau", "collection agency", "het"),
        ("deurwaarder", "bailiff", "de"),
        ("beslag", "seizure", "het"),
        ("faillissement", "bankruptcy", "het"),
        ("geldautomaten", "ATMs", "de"),
        ("bankfiliaal", "bank branch", "het"),
        ("online bankieren", "online banking", "het"),
        ("mobiel bankieren", "mobile banking", "het"),
        ("betaalverzoek", "payment request", "het"),
        ("periodieke betaling", "recurring payment", "de"),
        ("machtiging", "authorization", "de"),
        ("automatische incasso", "direct debit", "de"),
        ("acceptgiro", "giro transfer", "de"),
        ("overschrijving", "transfer", "de"),
        ("beschikbaar saldo", "available balance", "het"),
        ("kredietlimiet", "credit limit", "de"),
        ("maandelijkse lasten", "monthly expenses", "de"),
        ("vaste lasten", "fixed costs", "de"),
        ("variabele lasten", "variable costs", "de"),
        ("pinbetaling", "card payment", "de"),
        ("contactloos betalen", "contactless payment", "het"),
        ("mobiel betalen", "mobile payment", "het"),
        ("bankpas", "bank card", "de"),
        ("creditcard", "credit card", "de"),
        ("betaalpas", "payment card", "de"),
        ("daglimiet", "daily limit", "de"),
        ("opnamelimiet", "withdrawal limit", "de"),
        ("spaardoel", "savings goal", "het"),
        ("belegging", "investment", "de"),
        ("spaarrente", "savings interest", "de"),
        ("rentepercentage", "interest rate", "het"),
        ("jaarrente", "annual interest", "de"),
        ("maandrente", "monthly interest", "de"),
        ("geldopname", "withdrawal", "de"),
        ("storting", "deposit", "de"),
        ("betalingsherinnering", "payment reminder", "de"),
        ("incassokosten", "collection costs", "de"),
        ("boeterente", "penalty interest", "de"),
        ("spaarplan", "savings plan", "het"),
        ("termijndeposito", "term deposit", "het"),
        ("spaarrekeningrente", "savings account interest", "de"),
        ("consumptief krediet", "consumer credit", "het"),
        ("doorlopend krediet", "revolving credit", "het"),
        ("persoonlijke lening", "personal loan", "de"),
        ("consumptief lenen", "consumer lending", "het"),
        ("hypotheekadviseur", "mortgage adviser", "de"),
        ("financieel adviseur", "financial adviser", "de"),
        ("geldautomaat", "ATM", "de"),
        ("spaarbedrag", "savings amount", "het"),
    ],
    9: [  # Geschiedenis - 49 -> 150, need 101
        ("tijdperk", "era", "het"),
        ("periode", "period", "de"),
        ("tijdvak", "period", "het"),
        ("oudheid", "antiquity", "de"),
        ("middeleeuwen", "Middle Ages", "de"),
        ("renaissance", "Renaissance", "de"),
        ("verlichting", "Enlightenment", "de"),
        ("moderne tijd", "modern era", "de"),
        ("contemporain", "contemporary", None),
        ("prehistorie", "prehistory", "de"),
        ("steentijd", "Stone Age", "de"),
        ("ijzertijd", "Iron Age", "de"),
        ("romeinen", "Romans", "de"),
        ("romeins", "Roman", None),
        ("germanen", "Germanic tribes", "de"),
        ("vikingen", "Vikings", "de"),
        ("ridders", "knights", "de"),
        ("kastelen", "castles", "de"),
        ("kathedralen", "cathedrals", "de"),
        ("reformatie", "Reformation", "de"),
        ("tachtigjarige oorlog", "Eighty Years' War", "de"),
        ("gouden eeuw", "Golden Age", "de"),
        ("voc", "VOC", "de"),
        ("kolonialisme", "colonialism", "het"),
        ("slavernij", "slavery", "de"),
        ("afschaffing", "abolition", "de"),
        ("industrialisatie", "industrialization", "de"),
        ("eerste wereldoorlog", "First World War", "de"),
        ("tweede wereldoorlog", "Second World War", "de"),
        ("holocaust", "Holocaust", "de"),
        ("bezetting", "occupation", "de"),
        ("verzet", "resistance", "het"),
        ("verzetsstrijder", "resistance fighter", "de"),
        ("bevrijding", "liberation", "de"),
        ("wederopbouw", "reconstruction", "de"),
        ("jaren zestig", "sixties", "de"),
        ("protest", "protest", "het"),
        ("emancipatie", "emancipation", "de"),
        ("vrouwenemancipatie", "women's liberation", "de"),
        ("kinderbijslag", "child benefit", "de"),
        ("welvaartstaat", "welfare state", "de"),
        ("europese unie", "European Union", "de"),
        ("samenwerking", "cooperation", "de"),
        ("vredesbeweging", "peace movement", "de"),
        ("milieu", "environment", "het"),
        ("klimaat", "climate", "het"),
        ("duurzaamheid", "sustainability", "de"),
        ("immigratie", "immigration", "de"),
        ("multiculturalisme", "multiculturalism", "het"),
        ("integratie", "integration", "de"),
        ("geschiedschrijving", "historiography", "de"),
        ("historicus", "historian", "de"),
        ("bronnenonderzoek", "source research", "het"),
        ("primaire bron", "primary source", "de"),
        ("secundaire bron", "secondary source", "de"),
        ("oral history", "oral history", "de"),
        ("getuigenis", "testimony", "de"),
        ("ooggetuige", "eyewitness", "de"),
        ("overlever", "survivor", "de"),
        ("herdenking", "commemoration", "de"),
        ("dodenherdenking", "Remembrance Day", "de"),
        ("bevrijdingsdag", "Liberation Day", "de"),
        ("vlag", "flag", "de"),
        ("halfstok", "half-mast", None),
        ("twee minuten stilte", "two minutes silence", "de"),
        ("krans", "wreath", "de"),
        ("monument", "monument", "het"),
        ("standbeeld", "statue", "het"),
        ("plaquette", "plaque", "de"),
        ("gedenksteen", "memorial stone", "de"),
        ("herinneringscentrum", "memorial centre", "het"),
        ("kamp", "camp", "het"),
        ("concentratiekamp", "concentration camp", "het"),
        ("anne frank", "Anne Frank", "de"),
        ("dagboek", "diary", "het"),
        ("wereldoorlog", "world war", "de"),
        ("vredesverdrag", "peace treaty", "het"),
        ("revolutie", "revolution", "de"),
        ("opstand", "uprising", "de"),
        ("onafhankelijkheid", "independence", "de"),
        ("democratisering", "democratization", "de"),
        ("technologische vooruitgang", "technological progress", "de"),
        ("uitvinding", "invention", "de"),
        ("ontdekking", "discovery", "de"),
        ("expeditie", "expedition", "de"),
        ("ontdekkingsreiziger", "explorer", "de"),
        ("handelsroute", "trade route", "de"),
        ("specerijen", "spices", "de"),
        ("slavenhandel", "slave trade", "de"),
        ("koloniaal verleden", "colonial past", "het"),
        ("dekolonisatie", "decolonization", "de"),
        ("handelscompagnie", "trading company", "de"),
        ("abolitionisme", "abolitionism", "het"),
        ("vaderlandse geschiedenis", "national history", "de"),
        ("wereldgeschiedenis", "world history", "de"),
        ("tijdsgeest", "spirit of the times", "de"),
        ("historische context", "historical context", "de"),
        ("geschiedkundige", "historian", "de"),
        ("bronnenkritiek", "source criticism", "de"),
        ("historisch besef", "historical awareness", "het"),
        ("verlichtingsdenkers", "Enlightenment thinkers", "de"),
        ("verzuiling", "pillarization", "de"),
        ("staten-generaal", "States General", "de"),
        ("grondwet", "constitution", "de"),
        ("grondwetsherziening", "constitutional revision", "de"),
        ("stadhouders", "stadholders", "de"),
        ("republiek der zeven verenigde nederlanden", "Dutch Republic", "de"),
        ("bataven", "Batavians", "de"),
        ("romeinse tijd", "Roman period", "de"),
        ("middeleeuwse stad", "medieval town", "de"),
        ("gracht", "canal", "de"),
        ("vestingstad", "fortified town", "de"),
        ("handelsstad", "trading city", "de"),
        ("havenstad", "port city", "de"),
    ],
    10: [  # Samen leven - 58 -> 150, need 92
        ("samenleving", "society", "de"),
        ("gemeenschap", "community", "de"),
        ("buurt", "neighbourhood", "de"),
        ("wijk", "district", "de"),
        ("stad", "city", "de"),
        ("dorp", "village", "het"),
        ("provincie", "province", "de"),
        ("land", "country", "het"),
        ("burger", "citizen", "de"),
        ("inwoner", "inhabitant", "de"),
        ("medeburger", "fellow citizen", "de"),
        ("buren", "neighbours", "de"),
        ("buurtschap", "neighbourliness", "de"),
        ("straat", "street", "de"),
        ("blok", "block", "het"),
        ("flat", "apartment building", "de"),
        ("woningbouwvereniging", "housing association", "de"),
        ("vve", "homeowners association", "de"),
        ("huurdersvereniging", "tenants association", "de"),
        ("actiegroep", "action group", "de"),
        ("bewonerscommissie", "residents committee", "de"),
        ("wijkraad", "district council", "de"),
        ("gemeenteraad", "municipal council", "de"),
        ("democratie", "democracy", "de"),
        ("dictatuur", "dictatorship", "de"),
        ("vrijheid", "freedom", "de"),
        ("gelijkheid", "equality", "de"),
        ("rechtvaardigheid", "justice", "de"),
        ("solidariteit", "solidarity", "de"),
        ("participatie", "participation", "de"),
        ("burgerparticipatie", "citizen participation", "de"),
        ("referendum", "referendum", "het"),
        ("petitie", "petition", "de"),
        ("demonstratie", "demonstration", "de"),
        ("protest", "protest", "het"),
        ("staking", "strike", "de"),
        ("vakbond", "trade union", "de"),
        ("werkgeversorganisatie", "employers organization", "de"),
        ("belangenvereniging", "interest group", "de"),
        ("ngo", "NGO", "de"),
        ("goede doel", "charity", "het"),
        ("doneren", "to donate", None),
        ("vrijwilligerswerk", "volunteer work", "het"),
        ("mantelzorg", "informal care", "de"),
        ("zorg", "care", "de"),
        ("ouderenzorg", "elderly care", "de"),
        ("gehandicaptenzorg", "disability care", "de"),
        ("jeugdzorg", "youth care", "de"),
        ("geestelijke gezondheidszorg", "mental health care", "de"),
        ("thuiszorg", "home care", "de"),
        ("verpleeghuis", "nursing home", "het"),
        ("bejaardentehuis", "old people's home", "het"),
        ("kinderopvang", "childcare", "de"),
        ("peuterspeelzaal", "playgroup", "de"),
        ("sportvereniging", "sports club", "de"),
        ("muziekvereniging", "music society", "de"),
        ("theatergroep", "theatre group", "de"),
        ("leeskring", "book club", "de"),
        ("hobbyclub", "hobby club", "de"),
        ("ontmoetingsplek", "meeting place", "de"),
        ("buurthuis", "community centre", "het"),
        ("bibliotheek", "library", "de"),
        ("cultureel centrum", "cultural centre", "het"),
        ("sportcomplex", "sports complex", "het"),
        ("speeltuin", "playground", "de"),
        ("park", "park", "het"),
        ("groen", "green space", "het"),
        ("openbare ruimte", "public space", "de"),
        ("veiligheid", "safety", "de"),
        ("leefbaarheid", "livability", "de"),
        ("overlast", "nuisance", "de"),
        ("geluidsoverlast", "noise nuisance", "de"),
        ("burenruzie", "neighbour dispute", "de"),
        ("bemiddeling", "mediation", "de"),
        ("conflict", "conflict", "het"),
        ("oplossing", "solution", "de"),
        ("buurtfeest", "street party", "het"),
        ("straatfeest", "street festival", "het"),
        ("buurtbarbecue", "neighbourhood barbecue", "de"),
        ("open dag", "open day", "de"),
        ("inloop", "drop-in", "de"),
        ("activiteit", "activity", "de"),
        ("evenement", "event", "het"),
        ("festival", "festival", "het"),
        ("markt", "market", "de"),
        ("weekmarkt", "weekly market", "de"),
        ("kerstmarkt", "Christmas market", "de"),
        ("rommelmarkt", "flea market", "de"),
        ("gezamenlijk", "joint", None),
        ("collectief", "collective", None),
        ("samenhorigheid", "solidarity", "de"),
        ("verbondenheid", "connectedness", "de"),
        ("wederzijdse hulp", "mutual aid", "de"),
        ("burenhulp", "neighbour help", "de"),
        ("buurtinitiatief", "neighbourhood initiative", "het"),
        ("wijkagent", "community police officer", "de"),
        ("buurtpreventie", "neighbourhood watch", "de"),
        ("buurtapp", "neighbourhood app", "de"),
        ("buurtwhatsapp", "neighbourhood WhatsApp", "de"),
        ("buurtbbq", "neighbourhood BBQ", "de"),
        ("gezamenlijke tuin", "shared garden", "de"),
        ("speeltuinvereniging", "playground association", "de"),
        ("buurtbudget", "neighbourhood budget", "het"),
        ("participatiebudget", "participation budget", "het"),
        ("bewonersavond", "residents evening", "de"),
        ("wijkbijeenkomst", "district meeting", "de"),
        ("buurtondersteuning", "neighbourhood support", "de"),
        ("mantelzorgondersteuning", "informal care support", "de"),
        ("vrijwilligerscentrale", "volunteer centre", "de"),
        ("buurtcontact", "neighbourhood contact", "het"),
        ("buurtgenoot", "neighbour", "de"),
        ("straatgenoot", "neighbour", "de"),
    ],
}


def main():
    with open(WINDMEE_PATH) as f:
        data = json.load(f)

    # First: remove duplicates (keep first occurrence per theme)
    seen_by_theme = {}
    deduped = []
    for v in data["vocab"]:
        t = v["theme"]
        key = v["nl"].lower().strip()
        if t not in seen_by_theme:
            seen_by_theme[t] = set()
        if key in seen_by_theme[t]:
            continue
        seen_by_theme[t].add(key)
        deduped.append(v)

    # Build by theme
    existing_by_theme = {}
    for v in deduped:
        t = v["theme"]
        if t not in existing_by_theme:
            existing_by_theme[t] = []
        existing_by_theme[t].append(v)

    # Global dedup: keep each word only in first theme where it appears
    seen_global = set()
    new_vocab = []
    for theme_id in range(1, 11):
        existing = existing_by_theme.get(theme_id, [])
        theme_words = set()
        for v in existing:
            key = v["nl"].lower().strip()
            if key not in seen_global:
                new_vocab.append(v)
                seen_global.add(key)
                theme_words.add(key)
        needed = max(0, MIN_PER_THEME - len(theme_words))

        if theme_id in EXTRA_VOCAB and needed > 0:
            max_id = max(
                (int(v["id"].split("_")[1]) for v in existing),
                default=-1,
            )
            added = 0
            for nl, en, article in EXTRA_VOCAB[theme_id]:
                if added >= needed:
                    break
                key = nl.lower().strip()
                if key in theme_words or key in seen_global:
                    continue
                max_id += 1
                new_vocab.append({
                    "id": f"w{theme_id:02d}_{max_id:04d}",
                    "theme": theme_id,
                    "nl": nl,
                    "article": article,
                    "en": en,
                    "tags": [],
                })
                theme_words.add(key)
                seen_global.add(key)
                added += 1

    new_vocab.sort(key=lambda v: (v["theme"], v["id"]))
    data["vocab"] = new_vocab

    with open(WINDMEE_PATH, "w") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    from collections import Counter
    counts = Counter(v["theme"] for v in data["vocab"])
    print("Wind mee theme counts (min 150):")
    for t in sorted(counts.keys()):
        status = "✓" if counts[t] >= MIN_PER_THEME else "✗"
        print(f"  Theme {t}: {counts[t]} {status}")
    print(f"Total: {len(data['vocab'])} words")

    # Check for duplicates
    for t in range(1, 11):
        words = [v["nl"].lower() for v in data["vocab"] if v["theme"] == t]
        dups = [w for w in words if words.count(w) > 1]
        if dups:
            print(f"  WARNING: Duplicates in theme {t}: {set(dups)}")


if __name__ == "__main__":
    main()
