#!/usr/bin/env python3
"""
Add vocabulary to themes until each has at least 150 entries.
Uses thematic Dutch A1/A2 vocabulary.
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
COURSE_PATHS = [
    ROOT / "content" / "course.json",
    ROOT / "content" / "klimop.json",
    ROOT / "apps" / "web" / "public" / "content" / "klimop.json",
]
MIN_PER_THEME = 150

# Thematic vocabulary: (nl, en, article). Article: "de", "het", or None.
# Words chosen to fit each theme; script skips any that already exist in course.
THEME_VOCAB = {
    1: [  # Kennismaken - introductions, basic conversation
        ("achternaam", "surname", "de"),
        ("voornaam", "first name", "de"),
        ("beroep", "profession", "het"),
        ("leeftijd", "age", "de"),
        ("nationaliteit", "nationality", "de"),
        ("geboortedatum", "date of birth", "de"),
        ("geboorteplaats", "place of birth", "de"),
        ("postcode", "postcode", "de"),
        ("telefoonnummer", "phone number", "het"),
        ("e-mailadres", "email address", "het"),
        ("leerkracht", "teacher", "de"),
        ("formulier", "form", "het"),
        ("handtekening", "signature", "de"),
        ("paspoort", "passport", "het"),
        ("identiteitskaart", "ID card", "de"),
        ("visum", "visa", "het"),
        ("verblijfsvergunning", "residence permit", "de"),
        ("geslacht", "gender", "het"),
        ("burgerlijke staat", "marital status", "de"),
        ("geboorteland", "country of birth", "het"),
        ("wijk", "district", "de"),
        ("provincie", "province", "de"),
        ("regio", "region", "de"),
        ("dialect", "dialect", "het"),
        ("accent", "accent", "het"),
        ("uitspraak", "pronunciation", "de"),
        ("grammatica", "grammar", "de"),
        ("spelling", "spelling", "de"),
        ("cursus", "course", "de"),
        ("cursist", "course participant", "de"),
        ("docent", "teacher", "de"),
        ("klasgenoot", "classmate", "de"),
        ("studie", "study", "de"),
        ("opleiding", "education", "de"),
        ("diploma", "diploma", "het"),
        ("certificaat", "certificate", "het"),
        ("examen", "exam", "het"),
        ("toets", "test", "de"),
        ("huiswerk", "homework", "het"),
        ("lesrooster", "schedule", "het"),
        ("schooljaar", "school year", "het"),
        ("semester", "semester", "het"),
        ("trimester", "trimester", "het"),
        ("introductie", "introduction", "de"),
        ("presentatie", "presentation", "de"),
        ("netwerken", "to network", None),
        ("contactgegevens", "contact details", "de"),
        ("linkedin", "LinkedIn", None),
        ("profiel", "profile", "het"),
        ("foto", "photo", "de"),
        ("werkgever", "employer", "de"),
        ("werknemer", "employee", "de"),
        ("stage", "internship", "de"),
        ("sollicitatie", "job application", "de"),
        ("cv", "CV", "het"),
        ("sollicitatiebrief", "cover letter", "de"),
        ("vacature", "vacancy", "de"),
        ("arbeidscontract", "employment contract", "het"),
        ("proeftijd", "probation period", "de"),
        ("salaris", "salary", "het"),
        ("loon", "wage", "het"),
        ("pensioen", "pension", "het"),
        ("verlof", "leave", "het"),
        ("ziekmelding", "sick leave", "de"),
    ],
    2: [  # Hoe gaat het? - greetings, feelings, small talk
        ("gezondheid", "health", "de"),
        ("humor", "mood", "de"),
        ("gevoel", "feeling", "het"),
        ("emotie", "emotion", "de"),
        ("blij", "happy", None),
        ("verdrietig", "sad", None),
        ("boos", "angry", None),
        ("moe", "tired", None),
        ("energiek", "energetic", None),
        ("zenuwachtig", "nervous", None),
        ("ontspannen", "relaxed", None),
        ("gestrest", "stressed", None),
        ("optimistisch", "optimistic", None),
        ("pessimistisch", "pessimistic", None),
        ("enthousiast", "enthusiastic", None),
        ("verrast", "surprised", None),
        ("bezorgd", "worried", None),
        ("tevreden", "satisfied", None),
        ("ongelukkig", "unhappy", None),
        ("gelukkig", "happy", None),
        ("kalm", "calm", None),
        ("opgewonden", "excited", None),
        ("verveeld", "bored", None),
        ("nieuwsgierig", "curious", None),
        ("trots", "proud", None),
        ("verlegen", "shy", None),
        ("zelfverzekerd", "confident", None),
        ("onzeker", "uncertain", None),
        ("teleurgesteld", "disappointed", None),
        ("hoopvol", "hopeful", None),
        ("wanhopig", "desperate", None),
        ("gul", "generous", None),
        ("vriendelijk", "friendly", None),
        ("aardig", "nice", None),
        ("ruw", "rough", None),
        ("zacht", "soft", None),
        ("hard", "hard", None),
        ("warm", "warm", None),
        ("koud", "cold", None),
        ("gezelligheid", "coziness", "de"),
        ("sfeer", "atmosphere", "de"),
        ("gesprek", "conversation", "het"),
        ("onderwerp", "topic", "het"),
        ("mening", "opinion", "de"),
        ("advies", "advice", "het"),
        ("steun", "support", "de"),
        ("troost", "comfort", "de"),
        ("aanmoediging", "encouragement", "de"),
        ("compliment", "compliment", "het"),
        ("glimlach", "smile", "de"),
        ("lach", "laugh", "de"),
        ("huilen", "to cry", None),
        ("zuchten", "to sigh", None),
        ("juichen", "to cheer", None),
        ("klagen", "to complain", None),
        ("roddelen", "to gossip", None),
        ("flirten", "to flirt", None),
        ("empathie", "empathy", "de"),
        ("sympathie", "sympathy", "de"),
        ("medeleven", "compassion", "het"),
        ("begrip", "understanding", "het"),
        ("geduld", "patience", "het"),
        ("tolerantie", "tolerance", "de"),
        ("respect", "respect", "het"),
        ("vertrouwen", "trust", "het"),
        ("liefde", "love", "de"),
        ("vriendschap", "friendship", "de"),
        ("haat", "hatred", "de"),
        ("woede", "anger", "de"),
        ("vreugde", "joy", "de"),
        ("angst", "fear", "de"),
        ("verrassing", "surprise", "de"),
    ],
    3: [  # Familie - family members and relationships
        ("schoonmoeder", "mother-in-law", "de"),
        ("schoonvader", "father-in-law", "de"),
        ("schoonzus", "sister-in-law", "de"),
        ("zwager", "brother-in-law", "de"),
        ("stiefmoeder", "stepmother", "de"),
        ("stiefvader", "stepfather", "de"),
        ("stiefbroer", "stepbrother", "de"),
        ("stiefzus", "stepsister", "de"),
        ("pleegkind", "foster child", "het"),
        ("adoptiekind", "adopted child", "het"),
        ("peetvader", "godfather", "de"),
        ("peetmoeder", "godmother", "de"),
        ("petekind", "godchild", "het"),
        ("achterneef", "great-nephew", "de"),
        ("achternicht", "great-niece", "de"),
        ("overgrootvader", "great-grandfather", "de"),
        ("overgrootmoeder", "great-grandmother", "de"),
        ("achterkleinkind", "great-grandchild", "het"),
        ("verwantschap", "relationship", "de"),
        ("bloedverwant", "blood relative", "de"),
        ("familielid", "family member", "het"),
        ("tweeling", "twins", "de"),
        ("eenling", "only child", "de"),
        ("geboorte", "birth", "de"),
        ("huwelijk", "marriage", "het"),
        ("scheiding", "divorce", "de"),
        ("verloving", "engagement", "de"),
        ("trouwen", "to marry", None),
        ("scheiden", "to divorce", None),
        ("opvoeden", "to raise", None),
        ("opgroeien", "to grow up", None),
        ("verzorgen", "to care for", None),
        ("bezoeken", "to visit", None),
        ("bellen", "to call", None),
        ("schrijven", "to write", None),
        ("missen", "to miss", None),
        ("erfenis", "inheritance", "de"),
        ("testament", "will", "het"),
        ("familienaam", "family name", "de"),
        ("stamboom", "family tree", "de"),
        ("generatie", "generation", "de"),
        ("voorouder", "ancestor", "de"),
        ("nakomeling", "descendant", "de"),
        ("gezinsleven", "family life", "het"),
        ("opvoeding", "upbringing", "de"),
        ("gezinsplanning", "family planning", "de"),
    ],
    4: [  # Dagelijkse activiteiten - daily routines
        ("wekker", "alarm clock", "de"),
        ("douche", "shower", "de"),
        ("bad", "bath", "het"),
        ("tandenborstel", "toothbrush", "de"),
        ("tandpasta", "toothpaste", "de"),
        ("zeep", "soap", "de"),
        ("shampoo", "shampoo", "de"),
        ("handdoek", "towel", "de"),
        ("scheren", "to shave", None),
        ("aankleden", "to get dressed", None),
        ("uitkleden", "to undress", None),
        ("ontbijten", "to have breakfast", None),
        ("lunchen", "to have lunch", None),
        ("avondeten", "to have dinner", None),
        ("afwassen", "to do the dishes", None),
        ("stofzuigen", "to vacuum", None),
        ("opruimen", "to tidy up", None),
        ("wassen", "to wash", None),
        ("strijken", "to iron", None),
        ("koken", "to cook", None),
        ("boodschappen", "groceries", "de"),
        ("boodschappenlijst", "shopping list", "de"),
        ("recept", "recipe", "het"),
        ("ingrediënt", "ingredient", "het"),
        ("oven", "oven", "de"),
        ("fornuis", "stove", "het"),
        ("koelkast", "fridge", "de"),
        ("vriezer", "freezer", "de"),
        ("afval", "garbage", "het"),
        ("recycling", "recycling", "de"),
        ("planten", "to water plants", None),
        ("tuinieren", "to garden", None),
        ("fietsen", "to cycle", None),
        ("wandelen", "to walk", None),
        ("hardlopen", "to run", None),
        ("sporten", "to exercise", None),
        ("gymnastiek", "gymnastics", "de"),
        ("yoga", "yoga", "de"),
        ("mediteren", "to meditate", None),
        ("slapen", "to sleep", None),
        ("wakker worden", "to wake up", None),
        ("uitrusten", "to rest", None),
        ("ontspannen", "to relax", None),
        ("televisie kijken", "to watch TV", None),
        ("muziek luisteren", "to listen to music", None),
        ("lezen", "to read", None),
        ("schrijven", "to write", None),
        ("studeren", "to study", None),
        ("werken", "to work", None),
        ("wekkertje", "alarm", "het"),
        ("badkamer", "bathroom", "de"),
        ("slaapkamer", "bedroom", "de"),
        ("woonkamer", "living room", "de"),
        ("keuken", "kitchen", "de"),
        ("wasmachine", "washing machine", "de"),
        ("droger", "dryer", "de"),
        ("vaatwasser", "dishwasher", "de"),
        ("stofzuiger", "vacuum cleaner", "de"),
        ("strijkijzer", "iron", "het"),
        ("afwasborstel", "dish brush", "de"),
        ("schoonmaakmiddel", "cleaning product", "het"),
        ("wasmiddel", "laundry detergent", "het"),
        ("weekritme", "weekly routine", "het"),
        ("dagindeling", "daily schedule", "de"),
        ("ochtendritueel", "morning routine", "het"),
        ("avondritueel", "evening routine", "het"),
        ("haar wassen", "to wash hair", None),
        ("gezicht wassen", "to wash face", None),
        ("tanden poetsen", "to brush teeth", None),
        ("kleren aandoen", "to put on clothes", None),
        ("bed opmaken", "to make bed", None),
        ("vuilnis buiten zetten", "to take out trash", None),
        ("post ophalen", "to get mail", None),
        ("krant lezen", "to read newspaper", None),
        ("hond uitlaten", "to walk dog", None),
        ("koffie zetten", "to make coffee", None),
        ("thee drinken", "to drink tea", None),
        ("lunch klaarmaken", "to prepare lunch", None),
        ("boodschappen doen", "to do groceries", None),
        ("dagelijkse routine", "daily routine", "de"),
        ("wekelijkse taken", "weekly tasks", "de"),
    ],
    5: [  # De tijd - time expressions
        ("seconde", "second", "de"),
        ("minuut", "minute", "de"),
        ("uur", "hour", "het"),
        ("dag", "day", "de"),
        ("week", "week", "de"),
        ("maand", "month", "de"),
        ("jaar", "year", "het"),
        ("decennium", "decade", "het"),
        ("eeuw", "century", "de"),
        ("ochtend", "morning", "de"),
        ("middag", "afternoon", "de"),
        ("avond", "evening", "de"),
        ("nacht", "night", "de"),
        ("middernacht", "midnight", "de"),
        ("middag", "noon", "de"),
        ("zonsopgang", "sunrise", "de"),
        ("zonsondergang", "sunset", "de"),
        ("seizoen", "season", "het"),
        ("lente", "spring", "de"),
        ("zomer", "summer", "de"),
        ("herfst", "autumn", "de"),
        ("winter", "winter", "de"),
        ("maandag", "Monday", "de"),
        ("dinsdag", "Tuesday", "de"),
        ("woensdag", "Wednesday", "de"),
        ("donderdag", "Thursday", "de"),
        ("vrijdag", "Friday", "de"),
        ("zaterdag", "Saturday", "de"),
        ("zondag", "Sunday", "de"),
        ("januari", "January", "de"),
        ("februari", "February", "de"),
        ("maart", "March", "de"),
        ("april", "April", "de"),
        ("mei", "May", "de"),
        ("juni", "June", "de"),
        ("juli", "July", "de"),
        ("augustus", "August", "de"),
        ("september", "September", "de"),
        ("oktober", "October", "de"),
        ("november", "November", "de"),
        ("december", "December", "de"),
        ("verjaardag", "birthday", "de"),
        ("feestdag", "holiday", "de"),
        ("vakantie", "vacation", "de"),
        ("afspraak", "appointment", "de"),
        ("deadline", "deadline", "de"),
        ("tijdschema", "schedule", "het"),
        ("agenda", "agenda", "de"),
        ("kalender", "calendar", "de"),
        ("klok", "clock", "de"),
        ("horloge", "watch", "het"),
        ("kwartier", "quarter", "het"),
        ("halfuur", "half hour", "het"),
        ("ochtendgloren", "dawn", "het"),
        ("schemering", "dusk", "de"),
        ("tijdstip", "point in time", "het"),
        ("tijdzone", "time zone", "de"),
        ("zomertijd", "summer time", "de"),
        ("wintertijd", "winter time", "de"),
        ("jaarwisseling", "New Year", "de"),
        ("oudjaar", "New Year's Eve", "het"),
        ("nieuwjaar", "New Year's Day", "het"),
        ("pasen", "Easter", "het"),
        ("kerstmis", "Christmas", "de"),
        ("sinterklaas", "Sinterklaas", "de"),
        ("koningsdag", "King's Day", "de"),
        ("herdenkingsdag", "memorial day", "de"),
        ("vrije dag", "day off", "de"),
        ("werkdag", "workday", "de"),
        ("weekdag", "weekday", "de"),
        ("feestdag", "public holiday", "de"),
        ("verlofdag", "leave day", "de"),
        ("ziekedag", "sick day", "de"),
        ("tijdsduur", "duration", "de"),
        ("tijdspanne", "time span", "de"),
        ("verleden", "past", "het"),
        ("heden", "present", "het"),
        ("toekomst", "future", "de"),
        ("voortgang", "progress", "de"),
        ("vertraging", "delay", "de"),
        ("versnelling", "acceleration", "de"),
        ("pauze", "break", "de"),
        ("onderbreking", "interruption", "de"),
        ("voortzetting", "continuation", "de"),
        ("einde", "end", "het"),
        ("begin", "beginning", "het"),
        ("start", "start", "de"),
        ("finish", "finish", "de"),
        ("deadline", "deadline", "de"),
        ("tijdig", "timely", None),
        ("laat", "late", None),
        ("vroeg", "early", None),
        ("tijdrekening", "time reckoning", "de"),
        ("tijdsaanduiding", "time indication", "de"),
        ("uurwerk", "timepiece", "het"),
        ("chronometer", "chronometer", "de"),
        ("stopwatch", "stopwatch", "de"),
    ],
    6: [  # Afspreken - making appointments
        ("afspraak", "appointment", "de"),
        ("vergadering", "meeting", "de"),
        ("agenda", "agenda", "de"),
        ("beschikbaar", "available", None),
        ("bezet", "busy", None),
        ("vrij", "free", None),
        ("plannen", "to plan", None),
        ("annuleren", "to cancel", None),
        ("uitstellen", "to postpone", None),
        ("verzetten", "to reschedule", None),
        ("bevestigen", "to confirm", None),
        ("herinneren", "to remind", None),
        ("herinnering", "reminder", "de"),
        ("notificatie", "notification", "de"),
        ("locatie", "location", "de"),
        ("adres", "address", "het"),
        ("route", "route", "de"),
        ("richting", "direction", "de"),
        ("kaart", "map", "de"),
        ("navigatie", "navigation", "de"),
        ("parkeerplaats", "parking", "de"),
        ("ingang", "entrance", "de"),
        ("uitgang", "exit", "de"),
        ("receptie", "reception", "de"),
        ("wachtkamer", "waiting room", "de"),
        ("spreekkamer", "consultation room", "de"),
        ("kantoor", "office", "het"),
        ("conferentiezaal", "conference room", "de"),
        ("vergaderzaal", "meeting room", "de"),
        ("reserveren", "to reserve", None),
        ("boeken", "to book", None),
        ("inschrijven", "to register", None),
        ("aanmelden", "to sign up", None),
        ("afmelden", "to cancel", None),
        ("deelnemen", "to participate", None),
        ("aanwezig", "present", None),
        ("afwezig", "absent", None),
        ("afspraak maken", "to make an appointment", None),
        ("afspraak afzeggen", "to cancel appointment", None),
        ("tijdstip", "time slot", "het"),
        ("beschikbaarheid", "availability", "de"),
        ("optijd", "on time", None),
        ("te laat", "late", None),
        ("wachtlijst", "waiting list", "de"),
        ("doorverwijzing", "referral", "de"),
        ("afspraakbevestiging", "appointment confirmation", "de"),
    ],
    7: [  # Eten en drinken - food and drink
        ("voedsel", "food", "het"),
        ("drank", "drink", "de"),
        ("maaltijd", "meal", "de"),
        ("hapje", "snack", "het"),
        ("dessert", "dessert", "het"),
        ("voorgerecht", "starter", "het"),
        ("hoofdgerecht", "main course", "het"),
        ("nagerecht", "dessert", "het"),
        ("recept", "recipe", "het"),
        ("kruiden", "herbs", "de"),
        ("specerijen", "spices", "de"),
        ("zout", "salt", "het"),
        ("peper", "pepper", "de"),
        ("suiker", "sugar", "de"),
        ("olie", "oil", "de"),
        ("azijn", "vinegar", "de"),
        ("saus", "sauce", "de"),
        ("marinade", "marinade", "de"),
        ("dressing", "dressing", "de"),
        ("boter", "butter", "de"),
        ("margarine", "margarine", "de"),
        ("jam", "jam", "de"),
        ("honing", "honey", "de"),
        ("pindakaas", "peanut butter", "de"),
        ("chocoladepasta", "chocolate spread", "de"),
        ("muesli", "muesli", "de"),
        ("cornflakes", "cornflakes", "de"),
        ("havermout", "oatmeal", "de"),
        ("mayonaise", "mayonnaise", "de"),
        ("mosterd", "mustard", "de"),
        ("ketchup", "ketchup", "de"),
        ("ketjap", "soy sauce", "de"),
        ("tahin", "tahini", "de"),
        ("hummus", "hummus", "de"),
        ("pesto", "pesto", "de"),
        ("kruidenmix", "herb mix", "de"),
        ("bouillon", "stock", "de"),
        ("bouillonblokje", "stock cube", "het"),
        ("maïzena", "cornstarch", "de"),
        ("bakpoeder", "baking powder", "het"),
        ("vanille", "vanilla", "de"),
        ("kaneel", "cinnamon", "de"),
        ("nootmuskaat", "nutmeg", "de"),
        ("gember", "ginger", "de"),
        ("knoflook", "garlic", "de"),
        ("ui", "onion", "de"),
    ],
    9: [  # Winkelen - shopping
        ("winkel", "shop", "de"),
        ("winkelcentrum", "shopping center", "het"),
        ("winkelstraat", "shopping street", "de"),
        ("etalage", "shop window", "de"),
        ("kassa", "cash register", "de"),
        ("pinautomaat", "ATM", "de"),
        ("betaalpas", "debit card", "de"),
        ("creditcard", "credit card", "de"),
        ("contant", "cash", None),
        ("wisselgeld", "change", "het"),
        ("bon", "receipt", "de"),
        ("garantie", "warranty", "de"),
        ("retourneren", "to return", None),
        ("ruilen", "to exchange", None),
        ("korting", "discount", "de"),
        ("uitverkoop", "sale", "de"),
        ("aanbieding", "offer", "de"),
        ("prijs", "price", "de"),
        ("tweedehands", "second-hand", None),
        ("nieuw", "new", None),
        ("passen", "to try on", None),
        ("maat", "size", "de"),
        ("kleur", "color", "de"),
        ("voorraad", "stock", "de"),
        ("bestelling", "order", "de"),
        ("levering", "delivery", "de"),
        ("bezorging", "delivery", "de"),
        ("bezorgen", "to deliver", None),
        ("ophalen", "to pick up", None),
        ("verpakking", "packaging", "de"),
        ("verzendkosten", "shipping costs", "de"),
        ("gratis verzending", "free shipping", "de"),
        ("webwinkel", "web shop", "de"),
        ("online bestellen", "to order online", None),
        ("klantenservice", "customer service", "de"),
        ("reclamatie", "complaint", "de"),
    ],
}


def get_max_id(course: dict, theme: int) -> int:
    prefix = f"t{theme:02d}_"
    max_id = -1
    for v in course["vocab"]:
        if v["theme"] == theme and v["id"].startswith(prefix):
            try:
                num = int(v["id"].split("_")[1])
                max_id = max(max_id, num)
            except (IndexError, ValueError):
                pass
    return max_id


def get_existing_nl(course: dict) -> set:
    return {v["nl"].lower().strip() for v in course["vocab"]}


def main():
    with open(COURSE_PATHS[0], "r", encoding="utf-8") as f:
        course = json.load(f)

    existing = get_existing_nl(course)
    added_total = 0

    for theme_id, words in THEME_VOCAB.items():
        theme_vocab = [v for v in course["vocab"] if v["theme"] == theme_id]
        current_count = len(theme_vocab)
        needed = max(0, MIN_PER_THEME - current_count)

        if needed == 0:
            print(f"Theme {theme_id}: already {current_count} (>= {MIN_PER_THEME})")
            continue

        max_id = get_max_id(course, theme_id)
        added = 0

        for nl, en, article in words:
            if added >= needed:
                break
            if nl.lower().strip() in existing:
                continue

            max_id += 1
            entry = {
                "id": f"t{theme_id:02d}_{max_id:04d}",
                "theme": theme_id,
                "nl": nl,
                "article": article,
                "en": en,
                "tags": [],
            }
            course["vocab"].append(entry)
            existing.add(nl.lower().strip())
            added += 1

        new_count = current_count + added
        print(f"Theme {theme_id}: {current_count} -> {new_count} (+{added})")
        added_total += added

    # Sort vocab: keep themes together, by id within theme
    course["vocab"].sort(key=lambda v: (v["theme"], v["id"]))

    for path in COURSE_PATHS:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(course, f, ensure_ascii=False, indent=2)

    print(f"\nTotal added: {added_total}")

    # Verify
    from collections import Counter
    counts = Counter(v["theme"] for v in course["vocab"])
    print("\nFinal counts per theme:")
    for t in sorted(counts.keys()):
        status = "✓" if counts[t] >= MIN_PER_THEME else "✗"
        print(f"  Theme {t}: {counts[t]} {status}")


if __name__ == "__main__":
    main()
