#!/usr/bin/env python3
"""
Bring each Wind mee theme to at least 200 words. No duplicates (case-insensitive per theme).
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
WINDMEE_PATH = ROOT / "apps" / "web" / "public" / "content" / "windmee.json"
MIN_PER_THEME = 200

# Additional words per theme to reach 150+. Format: (nl, en, article)
# Only words not already in the theme. Script skips duplicates.
EXTRA_VOCAB = {
    1: [  # Wonen - 95 -> 150, need 55
        ("raam", "window", "het"),
        ("vloer", "floor", "de"),
        ("plafond", "ceiling", "het"),
        ("muur", "wall", "de"),
        ("licht", "light", "het"),
        ("stopcontact", "socket", "het"),
        ("schakelaar", "switch", "de"),
        ("radiator", "radiator", "de"),
        ("afvoer", "drain", "de"),
        ("douchekop", "shower head", "de"),
        ("handzeep", "hand soap", "de"),
        ("wastafelkastje", "bathroom cabinet", "het"),
        ("badmat", "bath mat", "de"),
        ("handdoekrek", "towel rack", "het"),
        ("wastafel", "sink", "de"),
        ("afvalbak", "waste bin", "de"),
        ("plant", "plant", "de"),
        ("boekenkast", "bookshelf", "de"),
        ("tv-meubel", "TV stand", "het"),
        ("bankstel", "sofa set", "het"),
        ("eetkamer", "dining room", "de"),
        ("berging", "storage", "de"),
        ("wasplaats", "utility room", "de"),
        ("droogrek", "drying rack", "het"),
        ("waslijn", "clothes line", "de"),
        ("stofzuiger", "vacuum cleaner", "de"),
        ("emmer", "bucket", "de"),
        ("dweil", "mop", "de"),
        ("bezem", "broom", "de"),
        ("schoonmaken", "to clean", None),
        ("opruimen", "to tidy", None),
        ("stof afnemen", "to dust", None),
        ("ramen zemen", "to clean windows", None),
        ("vuilnis", "garbage", "het"),
        ("recyclen", "to recycle", None),
        ("composteren", "to compost", None),
        ("tuinmeubel", "garden furniture", "het"),
        ("parasol", "parasol", "de"),
        ("ligstoel", "sun lounger", "de"),
        ("barbecue", "barbecue", "de"),
        ("schutting", "fence", "de"),
        ("hek", "gate", "het"),
        ("oprit", "driveway", "de"),
        ("voordeur", "front door", "de"),
        ("achterdeur", "back door", "de"),
        ("deurbel", "doorbell", "de"),
        ("sleutel", "key", "de"),
        ("slot", "lock", "het"),
        ("intercom", "intercom", "de"),
        ("deurmat", "doormat", "de"),
        ("kapstok", "coat rack", "de"),
        ("schoenenkast", "shoe cabinet", "de"),
        ("gang", "hallway", "de"),
        ("overloop", "landing", "de"),
        ("zolder", "attic", "de"),
        ("kelder", "cellar", "de"),
        ("traploper", "stair runner", "de"),
        ("vensterbank", "windowsill", "de"),
        ("gordijn", "curtain", "het"),
        ("lampenkap", "lampshade", "de"),
        ("spiegel", "mirror", "de"),
        ("spiegellijst", "mirror frame", "de"),
        ("wandlamp", "wall lamp", "de"),
        ("staande lamp", "floor lamp", "de"),
        ("bureaulamp", "desk lamp", "de"),
        ("nachtlampje", "night light", "het"),
        ("verwarming", "heating", "de"),
        ("thermostaat", "thermostat", "de"),
        ("airco", "air conditioning", "de"),
        ("ventilator", "fan", "de"),
        ("afzuigkap", "extractor hood", "de"),
        ("fornuis", "stove", "het"),
        ("oven", "oven", "de"),
        ("magnetron", "microwave", "de"),
        ("koelkast", "fridge", "de"),
        ("vriezer", "freezer", "de"),
        ("vaatwasser", "dishwasher", "de"),
        ("wasmachine", "washing machine", "de"),
        ("droger", "tumble dryer", "de"),
        ("strijkijzer", "iron", "het"),
        ("strijkplank", "ironing board", "de"),
        ("naaimachine", "sewing machine", "de"),
        ("gordijnrail", "curtain rail", "de"),
        ("jaloezie", "blinds", "de"),
        ("rolgordijn", "roller blind", "het"),
        ("vloerkleed", "rug", "het"),
        ("tapijt", "carpet", "het"),
        ("parket", "parquet", "het"),
        ("laminaat", "laminate", "het"),
        ("tegel", "tile", "de"),
        ("behang", "wallpaper", "het"),
        ("verf", "paint", "de"),
        ("kwast", "brush", "de"),
        ("roller", "roller", "de"),
        ("ladder", "ladder", "de"),
        ("kruipruimte", "crawl space", "de"),
        ("cv-ketel", "boiler", "de"),
        ("watermeter", "water meter", "de"),
        ("gasmeter", "gas meter", "de"),
        ("elektriciteitsmeter", "electricity meter", "de"),
        ("hoofdschakelaar", "main switch", "de"),
        ("zekeringkast", "fuse box", "de"),
        ("verlengkabel", "extension cord", "de"),
        ("adapters", "adapters", "de"),
        ("usb-hub", "USB hub", "de"),
        ("lader", "charger", "de"),
        ("stekkerdoos", "power strip", "de"),
        ("schoorsteen", "chimney", "de"),
        ("dakgoot", "gutter", "de"),
        ("regenpijp", "downpipe", "de"),
        ("zonnepanelen", "solar panels", "de"),
        ("dakraam", "skylight", "het"),
        ("luik", "hatch", "het"),
        ("kelderdeur", "cellar door", "de"),
        ("binnenplaats", "courtyard", "de"),
        ("terras", "terrace", "het"),
        ("balkon", "balcony", "het"),
        ("loggia", "loggia", "de"),
        ("serre", "conservatory", "de"),
        ("tuinhuis", "garden shed", "het"),
        ("schuur", "barn", "de"),
        ("tuindeur", "garden door", "de"),
    ],
    2: [  # Sociale contacten - 66 -> 150, need 84
        ("contact", "contact", "het"),
        ("netwerk", "network", "het"),
        ("relatie", "relationship", "de"),
        ("vriendschap", "friendship", "de"),
        ("kennismaking", "introduction", "de"),
        ("ontmoeting", "meeting", "de"),
        ("afspraakje", "date", "het"),
        ("verjaardag", "birthday", "de"),
        ("jubileum", "anniversary", "het"),
        ("babyborrel", "baby shower", "de"),
        ("housewarming", "housewarming", "de"),
        ("reünie", "reunion", "de"),
        ("borrel", "drinks", "de"),
        ("etentje", "dinner", "het"),
        ("lunchafspraak", "lunch date", "de"),
        ("koffiedate", "coffee date", "de"),
        ("videobellen", "to video call", None),
        ("appen", "to message", None),
        ("reageren", "to respond", None),
        ("liken", "to like", None),
        ("delen", "to share", None),
        ("posten", "to post", None),
        ("chatten", "to chat", None),
        ("mailen", "to email", None),
        ("een bericht sturen", "to send a message", None),
        ("oproepen", "to call", None),
        ("bereikbaar", "reachable", None),
        ("onbereikbaar", "unreachable", None),
        ("druk", "busy", None),
        ("beschikbaar", "available", None),
        ("vrij", "free", None),
        ("gepland", "planned", None),
        ("spontaan", "spontaneous", None),
        ("formeel", "formal", None),
        ("hartelijk", "warm", None),
        ("vriendelijk", "friendly", None),
        ("attent", "thoughtful", None),
        ("gastvrij", "hospitable", None),
        ("gezelschap", "company", "het"),
        ("samen zijn", "to be together", None),
        ("afspreken met", "to meet with", None),
        ("langskomen", "to drop by", None),
        ("uitnodigen voor", "to invite for", None),
        ("bedanken", "to thank", None),
        ("feliciteren", "to congratulate", None),
        ("condoleren", "to condole", None),
        ("troosten", "to comfort", None),
        ("aanmoedigen", "to encourage", None),
        ("liefde", "love", "de"),
        ("vertrouwen", "trust", "het"),
        ("verbondenheid", "connection", "de"),
        ("solidariteit", "solidarity", "de"),
        ("empatisch", "empathetic", None),
        ("begripvol", "understanding", None),
        ("respectvol", "respectful", None),
        ("open", "open", None),
        ("eerlijk", "honest", None),
        ("oprecht", "sincere", None),
        ("warm", "warm", None),
        ("koel", "cool", None),
        ("afstandelijk", "distant", None),
        ("geïrriteerd", "irritated", None),
        ("boos", "angry", None),
        ("blijdschap", "joy", "de"),
        ("teleurstelling", "disappointment", "de"),
        ("verwachting", "expectation", "de"),
        ("spanning", "tension", "de"),
        ("ontspanning", "relaxation", "de"),
        ("gezelligheid", "coziness", "de"),
        ("sfeer", "atmosphere", "de"),
        ("moment", "moment", "het"),
        ("herinnering", "memory", "de"),
        ("foto", "photo", "de"),
        ("selfie", "selfie", "de"),
        ("groepsfoto", "group photo", "de"),
        ("verjaardagskaart", "birthday card", "de"),
        ("condoleancekaart", "condolence card", "de"),
        ("bericht", "message", "het"),
        ("gesprek", "conversation", "het"),
        ("dialoog", "dialogue", "de"),
        ("small talk", "small talk", "de"),
        ("onderwerp", "topic", "het"),
        ("gespreksstof", "conversation topic", "de"),
        ("kennismaken", "to get to know", None),
        ("weerzien", "reunion", "het"),
        ("afscheid", "farewell", "het"),
        ("tot ziens", "goodbye", None),
        ("tot later", "see you later", None),
        ("praatje", "chat", "het"),
        ("afspraakje", "date", "het"),
        ("kennismakingsgesprek", "introductory chat", "het"),
        ("verjaardagsvisite", "birthday visit", "de"),
        ("nieuwjaarsreceptie", "New Year reception", "de"),
        ("netwerkborrel", "networking drinks", "de"),
        ("collegiale sfeer", "collegial atmosphere", "de"),
        ("werkrelatie", "work relationship", "de"),
        ("privérelatie", "private relationship", "de"),
        ("langeafstandsrelatie", "long-distance relationship", "de"),
        ("kennissenkring", "circle of acquaintances", "de"),
        ("vriendengroep", "group of friends", "de"),
        ("familiekring", "family circle", "de"),
        ("schoonfamilie", "in-laws", "de"),
        ("schoonmoeder", "mother-in-law", "de"),
        ("schoonvader", "father-in-law", "de"),
        ("zwager", "brother-in-law", "de"),
        ("schoonzus", "sister-in-law", "de"),
        ("schoonzoon", "son-in-law", "de"),
        ("schoondochter", "daughter-in-law", "de"),
        ("petekind", "godchild", "het"),
        ("peetoom", "godfather", "de"),
        ("peettante", "godmother", "de"),
        ("getuige", "witness", "de"),
        ("trouwfeest", "wedding celebration", "het"),
        ("huwelijksreis", "honeymoon", "de"),
        ("verlovingsring", "engagement ring", "de"),
        ("trouwring", "wedding ring", "de"),
        ("bruiloft", "wedding", "de"),
        ("bruidspaar", "bridal couple", "het"),
        ("bruiloftsgast", "wedding guest", "de"),
        ("speech", "speech", "de"),
        ("toast", "toast", "de"),
        ("proost", "cheers", None),
        ("gezondheid", "health", "de"),
        ("verjaardagstaart", "birthday cake", "de"),
        ("kaarsjes uitblazen", "to blow out candles", None),
        ("wens", "wish", "de"),
        ("verjaardagslied", "birthday song", "het"),
        ("lang zal ze leven", "happy birthday to you", None),
        ("cadeaupapier", "wrapping paper", "het"),
        ("strik", "bow", "de"),
        ("verrassing", "surprise", "de"),
        ("verrassingsfeest", "surprise party", "het"),
        ("afscheidsfeest", "farewell party", "het"),
        ("pensioenfeest", "retirement party", "het"),
        ("promotiefeest", "promotion party", "het"),
        ("housewarming party", "housewarming party", "de"),
        ("open huis", "open house", "het"),
        ("inwijdingsfeest", "housewarming", "het"),
        ("gastheer", "host", "de"),
        ("gastvrouw", "hostess", "de"),
        ("gastenlijst", "guest list", "de"),
        ("uitnodigingskaart", "invitation card", "de"),
    ],
    3: [  # Onderwijs - 80 -> 150, need 70
        ("peuterspeelzaal", "playgroup", "de"),
        ("kleuterschool", "kindergarten", "de"),
        ("groep", "group", "de"),
        ("leerjaar", "school year", "het"),
        ("semester", "semester", "het"),
        ("trimester", "trimester", "het"),
        ("vakantie", "holiday", "de"),
        ("herfstvakantie", "autumn break", "de"),
        ("kerstvakantie", "Christmas break", "de"),
        ("voorjaarsvakantie", "spring break", "de"),
        ("zomervakantie", "summer holiday", "de"),
        ("studiedag", "study day", "de"),
        ("vrije dag", "day off", "de"),
        ("lesuur", "lesson", "het"),
        ("pauze", "break", "de"),
        ("speelkwartier", "playtime", "het"),
        ("schoolbel", "school bell", "de"),
        ("schoolplein", "schoolyard", "het"),
        ("klaslokaal", "classroom", "het"),
        ("directeur", "headteacher", "de"),
        ("conciërge", "caretaker", "de"),
        ("secretariaat", "office", "het"),
        ("kantine", "canteen", "de"),
        ("gymzaal", "gym", "de"),
        ("laboratorium", "laboratory", "het"),
        ("computerlokaal", "computer room", "het"),
        ("mediatheek", "media library", "de"),
        ("studieplek", "study space", "de"),
        ("werkstuk", "assignment", "het"),
        ("opdracht", "assignment", "de"),
        ("samenwerking", "collaboration", "de"),
        ("groepswerk", "group work", "het"),
        ("individueel", "individual", None),
        ("mondeling", "oral", None),
        ("schriftelijk", "written", None),
        ("multiple choice", "multiple choice", None),
        ("open vraag", "open question", "de"),
        ("tentamen", "exam", "het"),
        ("herkansing", "retake", "de"),
        ("tussentijdse toets", "midterm", "de"),
        ("eindcijfer", "final grade", "het"),
        ("gemiddelde", "average", "het"),
        ("slagen", "to pass", None),
        ("zakken", "to fail", None),
        ("cum laude", "with honours", None),
        ("propedeuse", "first year", "de"),
        ("bachelor", "bachelor", "de"),
        ("master", "master", "de"),
        ("doctoraal", "doctoral", None),
        ("promotie", "PhD", "de"),
        ("wetenschapper", "scientist", "de"),
        ("onderzoek", "research", "het"),
        ("scriptie", "thesis", "de"),
        ("dissertatie", "dissertation", "de"),
        ("begeleider", "supervisor", "de"),
        ("examinator", "examiner", "de"),
        ("commissie", "committee", "de"),
        ("studiepunten", "credits", "de"),
        ("ects", "ECTS", "de"),
        ("inschrijven", "to enroll", None),
        ("uitschrijven", "to deregister", None),
        ("collegegeld", "tuition fee", "het"),
        ("studiefinanciering", "student finance", "de"),
        ("studielening", "student loan", "de"),
        ("studentenov", "student travel", "de"),
        ("studentenvereniging", "student association", "de"),
        ("sorority", "sorority", "de"),
        ("studentenhuis", "student house", "het"),
        ("kamernet", "Kamernet", "het"),
        ("studiebeurs", "study grant", "de"),
        ("honours", "honours", "het"),
        ("minor", "minor", "de"),
        ("major", "major", "de"),
        ("keuzevak", "elective", "het"),
        ("verplicht vak", "required course", "het"),
        ("tentamenweek", "exam week", "de"),
        ("blok", "block", "het"),
        ("collegezaal", "lecture hall", "de"),
        ("hoorcollege", "lecture", "het"),
        ("werkcollege", "tutorial", "het"),
        ("practicum", "practical", "het"),
        ("stage", "internship", "de"),
        ("stagebedrijf", "internship company", "het"),
        ("afstudeerproject", "graduation project", "het"),
        ("bacheloropleiding", "bachelor programme", "de"),
        ("masteropleiding", "master programme", "de"),
        ("deeltijd", "part-time", None),
        ("voltijd", "full-time", None),
        ("duaal", "dual", None),
        ("studiebelasting", "study load", "de"),
        ("studielast", "study load", "de"),
        ("studieadviseur", "student adviser", "de"),
        ("decaan", "dean", "de"),
        ("examencommissie", "exam board", "de"),
        ("bindend studieadvies", "binding study advice", "het"),
        ("bsa", "BSA", "het"),
        ("tentamenregeling", "exam regulations", "de"),
        ("fraude", "fraud", "de"),
        ("spieken", "to cheat", None),
        ("plagiaat", "plagiarism", "het"),
        ("bronvermelding", "citation", "de"),
        ("literatuurlijst", "bibliography", "de"),
        ("voetnoot", "footnote", "de"),
        ("groepspresentatie", "group presentation", "de"),
        ("peer review", "peer review", "de"),
        ("tijdmanagement", "time management", "het"),
        ("studieplanning", "study planning", "de"),
        ("deadline", "deadline", "de"),
        ("uitstel", "postponement", "het"),
        ("herinnering", "reminder", "de"),
        ("planner", "planner", "de"),
        ("studieplan", "study plan", "het"),
        ("leerdoel", "learning objective", "het"),
        ("leeruitkomst", "learning outcome", "de"),
        ("studievaardigheid", "study skill", "de"),
        ("aantekening", "note", "de"),
        ("collegedictaat", "lecture notes", "het"),
        ("syllabus", "syllabus", "de"),
        ("reader", "reader", "de"),
        ("studiehandleiding", "study guide", "de"),
        ("tentamenstof", "exam material", "de"),
        ("tentamenbundel", "exam bundle", "de"),
        ("oefententamen", "practice exam", "het"),
        ("nakijken", "to mark", None),
        ("cijfer geven", "to grade", None),
        ("tentamencommissie", "exam board", "de"),
    ],
    4: [  # Werk zoeken - 63 -> 150, need 87
        ("arbeidsmarkt", "job market", "de"),
        ("vacaturebank", "job board", "de"),
        ("indeed", "Indeed", "de"),
        ("monsterboard", "Monsterboard", "het"),
        ("loopbaan", "career", "de"),
        ("carrièrestap", "career step", "de"),
        ("carrièreswitch", "career change", "de"),
        ("doorgroeimogelijkheid", "growth opportunity", "de"),
        ("doorgroei", "advancement", "de"),
        ("promotie", "promotion", "de"),
        ("salarisverhoging", "salary increase", "de"),
        ("bonus", "bonus", "de"),
        ("commissie", "commission", "de"),
        ("reiskostenvergoeding", "travel allowance", "de"),
        ("onkostenvergoeding", "expense allowance", "de"),
        ("pensioenopbouw", "pension build-up", "de"),
        ("vakantiedagen", "holiday days", "de"),
        ("adv-dagen", "days in lieu", "de"),
        ("ziektedagen", "sick days", "de"),
        ("ouderverlof", "parental leave", "het"),
        ("zwangerschapsverlof", "maternity leave", "het"),
        ("papaverlof", "paternity leave", "het"),
        ("sabbatical", "sabbatical", "de"),
        ("detachering", "secondment", "de"),
        ("zzp", "self-employed", "de"),
        ("freelancer", "freelancer", "de"),
        ("opdrachtgever", "client", "de"),
        ("opdrachtnemer", "contractor", "de"),
        ("uitzendbureau", "temp agency", "het"),
        ("uitzendkracht", "temp worker", "de"),
        ("vast contract", "permanent contract", "het"),
        ("tijdelijk contract", "temporary contract", "het"),
        ("nulurencontract", "zero-hours contract", "het"),
        ("stageplek", "internship place", "de"),
        ("meeloopdag", "shadow day", "de"),
        ("proefdag", "trial day", "de"),
        ("assessment", "assessment", "het"),
        ("assessmentdag", "assessment day", "de"),
        ("casus", "case", "de"),
        ("rollenspel", "role play", "het"),
        ("competentiegericht", "competency-based", None),
        ("gedragsgericht", "behavioral", None),
        ("sterke punten", "strengths", "de"),
        ("zwakke punten", "weaknesses", "de"),
        ("ontwikkelpunten", "development points", "de"),
        ("leiderschap", "leadership", "het"),
        ("communicatie", "communication", "de"),
        ("probleemoplossend", "problem-solving", None),
        ("analytisch", "analytical", None),
        ("resultaatgericht", "result-oriented", None),
        ("klantgericht", "customer-oriented", None),
        ("teamspeler", "team player", "de"),
        ("zelfstandigheid", "independence", "de"),
        ("flexibiliteit", "flexibility", "de"),
        ("stressbestendigheid", "stress resistance", "de"),
        ("multitasken", "to multitask", None),
        ("prioriteren", "to prioritize", None),
        ("deadlines halen", "to meet deadlines", None),
        ("kwaliteit leveren", "to deliver quality", None),
        ("feedback geven", "to give feedback", None),
        ("feedback ontvangen", "to receive feedback", None),
        ("evaluatie", "evaluation", "de"),
        ("functioneringsgesprek", "performance review", "het"),
        ("beoordelingsgesprek", "appraisal", "het"),
        ("ontslag", "dismissal", "het"),
        ("ontslag nemen", "to resign", None),
        ("ontslagen worden", "to be fired", None),
        ("opzegtermijn", "notice period", "de"),
        ("vrijwillig", "voluntary", None),
        ("gedwongen", "forced", None),
        ("reorganisatie", "reorganization", "de"),
        ("fusie", "merge", "de"),
        ("overname", "takeover", "de"),
        ("faillissement", "bankruptcy", "het"),
        ("vacature", "vacancy", "de"),
        ("functie-eisen", "job requirements", "de"),
        ("profiel", "profile", "het"),
        ("cv", "CV", "het"),
        ("sollicitatiebrief", "cover letter", "de"),
        ("aanbevelingsbrief", "reference letter", "de"),
        ("netwerken", "to network", None),
        ("informatiengesprek", "informational interview", "het"),
        ("sollicitatiegesprek", "job interview", "het"),
        ("assessment center", "assessment centre", "het"),
        ("sollicitatieprocedure", "application procedure", "de"),
        ("vacatureadvertentie", "job advertisement", "de"),
        ("sollicitatiedeadline", "application deadline", "de"),
        ("aanstellingsgesprek", "offer meeting", "het"),
        ("contractvoorstel", "contract proposal", "het"),
        ("onderhandelingspositie", "negotiating position", "de"),
        ("aanbod", "offer", "het"),
        ("arbeidsvoorwaarden", "terms of employment", "de"),
        ("startdatum", "start date", "de"),
        ("vacaturebank", "job board", "de"),
        ("sollicitatieprocedure", "application procedure", "de"),
        ("functieomschrijving", "job description", "de"),
        ("salarisindicatie", "salary indication", "de"),
        ("werkgever", "employer", "de"),
        ("werknemer", "employee", "de"),
        ("medewerker", "employee", "de"),
        ("collega", "colleague", "de"),
        ("team", "team", "het"),
        ("afdeling", "department", "de"),
        ("sector", "sector", "de"),
        ("branche", "sector", "de"),
        ("bedrijfstak", "industry", "de"),
        ("werkgeversvereniging", "employers association", "de"),
        ("vakbond", "trade union", "de"),
        ("cao", "collective agreement", "de"),
        ("loonafspraak", "wage agreement", "de"),
        ("indexatie", "indexation", "de"),
        ("salarisonderhandeling", "salary negotiation", "de"),
        ("salarisverhoging", "pay rise", "de"),
        ("jaarsalaris", "annual salary", "het"),
        ("maandsalaris", "monthly salary", "het"),
        ("brutosalaris", "gross salary", "het"),
        ("netsalaris", "net salary", "het"),
        ("salarisstrook", "payslip", "de"),
        ("loonstrook", "payslip", "de"),
        ("belastingaangifte", "tax return", "de"),
        ("jaaropgave", "annual statement", "de"),
        ("werkgeversverklaring", "employer statement", "de"),
        ("referentie", "reference", "de"),
        ("referentiecheck", "reference check", "de"),
        ("achtergrondonderzoek", "background check", "het"),
        ("screening", "screening", "de"),
        ("vertrouwelijk", "confidential", None),
        ("geheimhouding", "confidentiality", "de"),
        ("non-concurrentiebeding", "non-compete clause", "het"),
        ("proeftijd", "probation period", "de"),
        ("beoordelingsgesprek", "appraisal", "het"),
        ("ontwikkelgesprek", "development meeting", "het"),
        ("carrièrepad", "career path", "het"),
        ("doorgroeimogelijkheid", "growth opportunity", "de"),
        ("bijscholing", "training", "de"),
        ("cursus", "course", "de"),
        ("certificering", "certification", "de"),
        ("diploma", "diploma", "het"),
        ("ervaring", "experience", "de"),
        ("starter", "starter", "de"),
        ("senior", "senior", None),
        ("medior", "medior", None),
        ("junior", "junior", None),
        ("headhunter", "headhunter", "de"),
        ("wervingsbureau", "recruitment agency", "het"),
        ("motivatiebrief", "motivation letter", "de"),
        ("sollicitatieformulier", "application form", "het"),
        ("online solliciteren", "to apply online", None),
        ("sollicitatiegesprek voorbereiden", "to prepare for interview", None),
        ("vragen stellen", "to ask questions", None),
        ("onderhandelen over salaris", "to negotiate salary", None),
        ("aanbod accepteren", "to accept offer", None),
        ("sollicitatie afwijzen", "to reject application", None),
        ("sollicitatie aannemen", "to accept application", None),
        ("sollicitatie in behandeling", "application under review", None),
        ("sollicitatie in behandeling nemen", "to consider application", None),
        ("eerste gesprek", "first interview", "het"),
        ("tweede gesprek", "second interview", "het"),
        ("eindgesprek", "final interview", "het"),
        ("assessment", "assessment", "het"),
        ("assessmentdag", "assessment day", "de"),
        ("sollicitatiegesprek", "job interview", "het"),
        ("sollicitatiecommissie", "selection committee", "de"),
        ("sollicitatieprocedure", "application procedure", "de"),
        ("vacaturetekst", "job description", "de"),
        ("functieprofiel", "job profile", "het"),
    ],
    5: [  # Een dag op het werk - 62 -> 150, need 88
        ("werkdag", "workday", "de"),
        ("kantoordag", "office day", "de"),
        ("thuiswerkdag", "work from home day", "de"),
        ("starttijd", "start time", "de"),
        ("eindtijd", "end time", "de"),
        ("pauzetijd", "break time", "de"),
        ("lunchpauze", "lunch break", "de"),
        ("koffiepauze", "coffee break", "de"),
        ("rooster", "schedule", "het"),
        ("dienstrooster", "shift schedule", "het"),
        ("wisseldienst", "rotating shift", "de"),
        ("vroege dienst", "early shift", "de"),
        ("late dienst", "late shift", "de"),
        ("nachtdienst", "night shift", "de"),
        ("weekenddienst", "weekend shift", "de"),
        ("feestdagen", "public holidays", "de"),
        ("kantoorruimte", "office space", "de"),
        ("werkplek", "workstation", "de"),
        ("bureau", "desk", "het"),
        ("stoel", "chair", "de"),
        ("beeldscherm", "screen", "het"),
        ("toetsenbord", "keyboard", "het"),
        ("muis", "mouse", "de"),
        ("headset", "headset", "de"),
        ("webcam", "webcam", "de"),
        ("telefoon", "phone", "de"),
        ("intercom", "intercom", "de"),
        ("printer", "printer", "de"),
        ("scanner", "scanner", "de"),
        ("archiefkast", "filing cabinet", "de"),
        ("whiteboard", "whiteboard", "het"),
        ("flipover", "flip chart", "de"),
        ("beamer", "projector", "de"),
        ("vergaderruimte", "meeting room", "de"),
        ("conferentiezaal", "conference room", "de"),
        ("breakout room", "breakout room", "de"),
        ("kantine", "canteen", "de"),
        ("koffiehoek", "coffee corner", "de"),
        ("rookruimte", "smoking area", "de"),
        ("parkeerplaats", "parking", "de"),
        ("fietsenstalling", "bike shed", "de"),
        ("informatie", "information", "de"),
        ("documentatie", "documentation", "de"),
        ("handleiding", "manual", "de"),
        ("protocol", "protocol", "het"),
        ("procedure", "procedure", "de"),
        ("werkproces", "work process", "het"),
        ("workflow", "workflow", "de"),
        ("deadline", "deadline", "de"),
        ("prioriteit", "priority", "de"),
        ("urgent", "urgent", None),
        ("belangrijk", "important", None),
        ("routine", "routine", "de"),
        ("ad-hoc", "ad hoc", None),
        ("structureel", "structural", None),
        ("incident", "incident", "het"),
        ("crisis", "crisis", "de"),
        ("noodgeval", "emergency", "het"),
        ("back-up", "backup", "de"),
        ("vervanger", "replacement", "de"),
        ("waarneming", "acting", "de"),
        ("delegatie", "delegation", "de"),
        ("verantwoordelijkheid", "responsibility", "de"),
        ("bevoegdheid", "authority", "de"),
        ("hiërarchie", "hierarchy", "de"),
        ("leidinggevende", "manager", "de"),
        ("directeur", "director", "de"),
        ("ceo", "CEO", "de"),
        ("afdelingshoofd", "department head", "de"),
        ("teamleider", "team leader", "de"),
        ("projectleider", "project manager", "de"),
        ("stakeholder", "stakeholder", "de"),
        ("klant", "customer", "de"),
        ("leverancier", "supplier", "de"),
        ("partner", "partner", "de"),
        ("concurrent", "competitor", "de"),
        ("branche", "sector", "de"),
        ("markt", "market", "de"),
        ("bedrijf", "company", "het"),
        ("organisatie", "organization", "de"),
        ("vestiging", "branch", "de"),
        ("hoofdkantoor", "headquarters", "het"),
        ("werkoverleg", "work meeting", "het"),
        ("stand-up", "stand-up", "de"),
        ("retrospective", "retrospective", "de"),
        ("brainstorm", "brainstorm", "de"),
        ("idee", "idea", "het"),
        ("voorstel", "proposal", "het"),
        ("besluit", "decision", "het"),
        ("akkoord", "agreement", "het"),
        ("vergaderagenda", "meeting agenda", "de"),
        ("vergaderruimte reserveren", "to book meeting room", None),
        ("notities maken", "to take notes", None),
        ("actielijst", "action list", "de"),
        ("follow-up", "follow-up", "de"),
        ("werkoverleg", "work meeting", "het"),
        ("projectoverleg", "project meeting", "het"),
        ("kwartaaloverleg", "quarterly meeting", "het"),
        ("jaaroverzicht", "annual overview", "het"),
        ("werkplekinrichting", "workplace design", "de"),
        ("ergonomie", "ergonomics", "de"),
        ("bureausetup", "desk setup", "de"),
        ("thuiswerkplek", "home workspace", "de"),
        ("kantoorbenodigdheden", "office supplies", "de"),
        ("kantoorpand", "office building", "het"),
        ("werkdruk", "workload", "de"),
        ("kantoorcultuur", "office culture", "de"),
        ("vergadervoorzitter", "meeting chair", "de"),
        ("notulist", "minute taker", "de"),
        ("agendapunt", "agenda item", "het"),
        ("besluitvorming", "decision-making", "de"),
        ("consensus", "consensus", "de"),
        ("stemming", "vote", "de"),
        ("voorstel", "proposal", "het"),
        ("amendement", "amendment", "het"),
        ("uitstel", "postponement", "het"),
        ("afgelasting", "cancellation", "de"),
        ("verplaatsing", "rescheduling", "de"),
        ("aanwezigheidslijst", "attendance list", "de"),
        ("excuses", "apology", "de"),
        ("afwezig", "absent", None),
        ("ziekmelding", "sick leave", "de"),
        ("verlofaanvraag", "leave request", "de"),
        ("verlofdag", "leave day", "de"),
        ("compensatie", "compensation", "de"),
        ("overuren", "overtime", "de"),
        ("flexibele werktijden", "flexible hours", "de"),
        ("kernuren", "core hours", "de"),
        ("thuiswerkdag", "work from home day", "de"),
        ("hybride werken", "hybrid working", "het"),
        ("werkplek", "workplace", "de"),
        ("hotdesking", "hot desking", "het"),
        ("vaste plek", "fixed desk", "de"),
        ("privacy", "privacy", "de"),
        ("afleiding", "distraction", "de"),
        ("concentratie", "concentration", "de"),
        ("productiviteit", "productivity", "de"),
        ("efficiëntie", "efficiency", "de"),
        ("effectiviteit", "effectiveness", "de"),
        ("kpi", "KPI", "de"),
        ("target", "target", "het"),
        ("doelstelling", "objective", "de"),
        ("kwartaaldoel", "quarterly goal", "het"),
        ("jaardoel", "annual goal", "het"),
        ("voortgang", "progress", "de"),
        ("statusupdate", "status update", "de"),
        ("weekelijkse update", "weekly update", "de"),
        ("maandrapportage", "monthly report", "de"),
        ("kwartaalrapport", "quarterly report", "het"),
        ("jaarverslag", "annual report", "het"),
        ("presentatie", "presentation", "de"),
        ("slides", "slides", "de"),
        ("handout", "handout", "de"),
        ("vergaderstoel", "meeting chair", "de"),
        ("vergadertafel", "meeting table", "de"),
        ("microfoon", "microphone", "de"),
        ("videoconferentie", "video conference", "de"),
        ("teams", "Teams", "het"),
        ("zoom", "Zoom", "de"),
        ("scherm delen", "to share screen", None),
        ("breakout sessie", "breakout session", "de"),
        ("brainstorm sessie", "brainstorm session", "de"),
        ("workshop", "workshop", "de"),
        ("training", "training", "de"),
        ("teambuilding", "team building", "het"),
        ("vergaderkamer", "meeting room", "de"),
        ("conferentie", "conference", "de"),
        ("webinar", "webinar", "het"),
        ("presentatie geven", "to give presentation", None),
        ("feedback vragen", "to ask for feedback", None),
        ("vergaderdatum", "meeting date", "de"),
        ("vergadertijd", "meeting time", "de"),
        ("vergaderlocatie", "meeting location", "de"),
        ("vergaderdeelnemer", "meeting participant", "de"),
        ("vergaderuitnodiging", "meeting invitation", "de"),
        ("vergaderbevestiging", "meeting confirmation", "de"),
        ("vergaderruimte", "meeting room", "de"),
        ("vergaderzaal", "meeting hall", "de"),
        ("vergaderagenda", "meeting agenda", "de"),
        ("vergadernotulen", "meeting minutes", "de"),
        ("vergaderbesluit", "meeting decision", "het"),
        ("vergaderactie", "meeting action", "de"),
        ("vergaderpunten", "meeting points", "de"),
        ("vergaderresultaat", "meeting result", "het"),
        ("vergaderoverzicht", "meeting overview", "het"),
        ("vergadersamenvatting", "meeting summary", "de"),
        ("vergaderactiepunten", "meeting action points", "de"),
        ("vergaderdeadline", "meeting deadline", "de"),
        ("vergadervervolg", "meeting follow-up", "het"),
        ("standpunt", "position", "het"),
        ("mening", "opinion", "de"),
        ("voorstel", "proposal", "het"),
        ("besluit", "decision", "het"),
        ("vergaderkamer", "meeting room", "de"),
        ("conferentiezaal", "conference room", "de"),
        ("vergaderruimte", "meeting room", "de"),
        ("vergaderzaal", "meeting hall", "de"),
        ("vergaderagenda", "meeting agenda", "de"),
        ("gemeentelijke dienst", "municipal service", "de"),
        ("burgerzaken", "civil affairs", "de"),
        ("bevolkingsregister", "population register", "het"),
        ("persoonsgegevens", "personal data", "de"),
        ("privacywet", "privacy law", "de"),
        ("identiteitscontrole", "identity check", "de"),
        ("paspoortcontrole", "passport control", "de"),
        ("grenscontrole", "border control", "de"),
        ("douane", "customs", "de"),
        ("visumaanvraag", "visa application", "de"),
        ("vollmacht", "power of attorney", "de"),
        ("gevolmachtigde", "authorized representative", "de"),
        ("volmachtformulier", "power of attorney form", "het"),
        ("legalisatie", "legalization", "de"),
        ("migratiedienst", "migration service", "de"),
        ("vreemdelingendienst", "immigration service", "de"),
        ("paspoortdienst", "passport service", "de"),
        ("rijbewijsdienst", "driving licence service", "de"),
        ("burgerzaken", "civil affairs", "de"),
    ],
    6: [  # Officiële instanties - 54 -> 150, need 96
        ("migratiedienst", "migration service", "de"),
        ("vreemdelingendienst", "immigration service", "de"),
        ("paspoortdienst", "passport service", "de"),
        ("rijbewijsdienst", "driving licence service", "de"),
        ("bevolkingsregister", "population register", "het"),
        ("overheid", "government", "de"),
        ("instantie", "agency", "de"),
        ("dienst", "department", "de"),
        ("kantoor", "office", "het"),
        ("balie", "counter", "de"),
        ("loket", "window", "het"),
        ("openingstijden", "opening hours", "de"),
        ("wachtlijst", "waiting list", "de"),
        ("wachtijd", "waiting time", "de"),
        ("afspraak", "appointment", "de"),
        ("walk-in", "walk-in", "de"),
        ("online", "online", None),
        ("digitaal", "digital", None),
        ("papier", "paper", "het"),
        ("origineel", "original", None),
        ("kopie", "copy", "de"),
        ("gelegaliseerd", "legalized", None),
        ("vertaald", "translated", None),
        ("gewettigd", "certified", None),
        ("notaris", "notary", "de"),
        ("ambassade", "embassy", "de"),
        ("consulaat", "consulate", "het"),
        ("visum", "visa", "het"),
        ("verblijfsvergunning", "residence permit", "de"),
        ("arbeidsvergunning", "work permit", "de"),
        ("gezinshereniging", "family reunification", "de"),
        ("asiel", "asylum", "het"),
        ("vluchteling", "refugee", "de"),
        ("statushouder", "status holder", "de"),
        ("inburgeringsplicht", "integration requirement", "de"),
        ("inburgeringscursus", "integration course", "de"),
        ("taalcursus", "language course", "de"),
        ("niveau", "level", "het"),
        ("examen", "exam", "het"),
        ("certificaat", "certificate", "het"),
        ("diploma", "diploma", "het"),
        ("rijvaardigheid", "driving ability", "de"),
        ("theorie", "theory", "de"),
        ("praktijk", "practice", "de"),
        ("rijschool", "driving school", "de"),
        ("examencentrum", "exam centre", "het"),
        ("cbr", "CBR", "het"),
        ("gezondheidsverklaring", "health declaration", "de"),
        ("gezichtsvermogen", "eyesight", "het"),
        ("bril", "glasses", "de"),
        ("contactlenzen", "contact lenses", "de"),
        ("adres", "address", "het"),
        ("postcode", "postcode", "de"),
        ("woonplaats", "place of residence", "de"),
        ("nationaliteit", "nationality", "de"),
        ("geboorteland", "country of birth", "het"),
        ("burgerschap", "citizenship", "het"),
        ("dubbele nationaliteit", "dual nationality", "de"),
        ("naturalisatie", "naturalization", "de"),
        ("optie", "option", "de"),
        ("eerste verblijfsvergunning", "first residence permit", "de"),
        ("verlenging", "extension", "de"),
        ("verblijfsrecht", "right of residence", "het"),
        ("arbeidsrecht", "right to work", "het"),
        ("studievoucher", "study voucher", "de"),
        ("inburgeringslening", "integration loan", "de"),
        ("lening", "loan", "de"),
        ("terugbetalen", "to repay", None),
        ("vrijstelling", "exemption", "de"),
        ("kwijtschelding", "waiver", "de"),
        ("aanvraag", "application", "de"),
        ("indienen", "to submit", None),
        ("bevestiging", "confirmation", "de"),
        ("afwijzing", "rejection", "de"),
        ("bezwaar", "objection", "het"),
        ("beroep", "appeal", "het"),
        ("rechter", "judge", "de"),
        ("rechtbank", "court", "de"),
        ("advocaat", "lawyer", "de"),
        ("juridisch", "legal", None),
        ("migrant", "migrant", "de"),
        ("immigrant", "immigrant", "de"),
        ("emigrant", "emigrant", "de"),
        ("expat", "expat", "de"),
        ("pasfoto", "passport photo", "de"),
        ("vingerafdruk", "fingerprint", "de"),
        ("biometrie", "biometrics", "de"),
        ("chipkaart", "chip card", "de"),
        ("digid-activeren", "to activate DigiD", None),
        ("mijn overheid", "MijnOverheid", "de"),
        ("belastingaangifte", "tax return", "de"),
        ("toeslagen", "allowances", "de"),
        ("kinderbijslag", "child benefit", "de"),
        ("huurtoeslag", "rent allowance", "de"),
        ("zorgtoeslag", "healthcare allowance", "de"),
        ("geboorteaangifte", "birth registration", "de"),
        ("gezagsverklaring", "authority declaration", "de"),
        ("gezag", "custody", "het"),
        ("huwelijksaangifte", "marriage registration", "de"),
        ("overlijdensaangifte", "death registration", "de"),
        ("naamsvermelding", "name mention", "de"),
        ("achternaam", "surname", "de"),
        ("voornaam", "first name", "de"),
        ("tussenvoegsel", "middle name", "het"),
        ("identiteitskaart", "identity card", "de"),
        ("rijbewijsnr", "driving licence number", "het"),
        ("paspoortnummer", "passport number", "het"),
        ("vervaldatum", "expiry date", "de"),
        ("geldigheidsduur", "validity period", "de"),
        ("aanvraagprocedure", "application procedure", "de"),
        ("geboorteaangifte doen", "to register birth", None),
        ("paspoortaanvraag", "passport application", "de"),
        ("rijbewijsaanvraag", "driving licence application", "de"),
        ("verblijfsdocument", "residence document", "het"),
        ("vreemdelingenpolitie", "immigration police", "de"),
        ("ind", "IND", "de"),
        ("naturalisatieceremonie", "naturalization ceremony", "de"),
        ("eed afleggen", "to take an oath", None),
        ("burgerschap verkrijgen", "to obtain citizenship", None),
        ("gemeente", "municipality", "de"),
        ("provincie", "province", "de"),
        ("rijksoverheid", "national government", "de"),
        ("ministerie", "ministry", "het"),
        ("wet", "law", "de"),
        ("regeling", "regulation", "de"),
        ("besluit", "decision", "het"),
        ("verordening", "ordinance", "de"),
        ("subsidie", "subsidy", "de"),
        ("subsidieaanvraag", "subsidy application", "de"),
        ("vergunning", "permit", "de"),
        ("bouwvergunning", "building permit", "de"),
        ("omgevingsvergunning", "environmental permit", "de"),
        ("kvk", "Chamber of Commerce", "de"),
        ("btw-nummer", "VAT number", "het"),
        ("inschrijving", "registration", "de"),
        ("uittreksel kvk", "Chamber of Commerce extract", "het"),
        ("handtekening", "signature", "de"),
        ("paraaf", "initial", "de"),
        ("datum", "date", "de"),
        ("plaats", "place", "de"),
        ("ondertekening", "signing", "de"),
        ("volmacht", "power of attorney", "de"),
        ("gevolmachtigde", "authorized person", "de"),
        ("vertegenwoordiger", "representative", "de"),
        ("machtiging", "authorization", "de"),
        ("toestemming", "permission", "de"),
        ("akkoord", "agreement", "het"),
        ("overeenkomst", "agreement", "de"),
        ("contract", "contract", "het"),
        ("huurcontract", "rental contract", "het"),
        ("arbeidscontract", "employment contract", "het"),
        ("opzegging", "termination", "de"),
        ("aanmaning", "reminder", "de"),
        ("invordering", "collection", "de"),
        ("beslaglegging", "attachment", "de"),
        ("executie", "execution", "de"),
        ("gerechtsdeurwaarder", "bailiff", "de"),
        ("dagvaarding", "summons", "de"),
        ("rechtszaak", "lawsuit", "de"),
        ("getuige", "witness", "de"),
        ("verklaring", "statement", "de"),
        ("ed", "oath", "de"),
        ("legitimatiebewijs", "ID document", "het"),
        ("geboortebewijs", "birth certificate", "het"),
        ("verklaring van in leven zijn", "life certificate", "de"),
        ("huurdersverklaring", "tenant declaration", "de"),
        ("werkgeversverklaring", "employer declaration", "de"),
        ("inkomensverklaring", "income declaration", "de"),
        ("belastingverklaring", "tax declaration", "de"),
        ("woonadres", "residential address", "het"),
        ("postadres", "postal address", "het"),
        ("correspondentieadres", "correspondence address", "het"),
        ("geboortedatum", "date of birth", "de"),
        ("geboorteplaats", "place of birth", "de"),
    ],
    7: [  # Op reis door Nederland - 62 -> 150, need 88
        ("reizen", "to travel", None),
        ("treinreizen", "train travel", "het"),
        ("busreizen", "bus travel", "het"),
        ("vliegen", "to fly", None),
        ("varen", "to sail", None),
        ("fietsen", "to cycle", None),
        ("lopen", "to walk", None),
        ("rijden", "to drive", None),
        ("meerijden", "to ride along", None),
        ("lift", "lift", "de"),
        ("carpoolen", "to carpool", None),
        ("ov", "public transport", "het"),
        ("ns", "Dutch Railways", "de"),
        ("arriva", "Arriva", "de"),
        ("connexxion", "Connexxion", "de"),
        ("gvb", "GVB", "het"),
        ("ret", "RET", "de"),
        ("htm", "HTM", "de"),
        ("ov-chipkaart", "OV-chipkaart", "de"),
        ("anonieme ov-chipkaart", "anonymous card", "de"),
        ("persoonlijke ov-chipkaart", "personal card", "de"),
        ("saldo", "balance", "het"),
        ("opwaarderen", "to top up", None),
        ("inchecken", "to check in", None),
        ("uitchecken", "to check out", None),
        ("overstap", "transfer", "de"),
        ("overstaptijd", "transfer time", "de"),
        ("rechtstreeks", "direct", None),
        ("via", "via", None),
        ("vertrek", "departure", "het"),
        ("aankomst", "arrival", "de"),
        ("vertrektijd", "departure time", "de"),
        ("aankomsttijd", "arrival time", "de"),
        ("spoor", "track", "het"),
        ("perron", "platform", "het"),
        ("halte", "stop", "de"),
        ("eindhalte", "terminal", "de"),
        ("tussenstop", "stopover", "de"),
        ("vertraging", "delay", "de"),
        ("geen dienst", "no service", None),
        ("storing", "disruption", "de"),
        ("omleiding", "diversion", "de"),
        ("vervangend vervoer", "replacement transport", "het"),
        ("busvervangend vervoer", "replacement bus", "het"),
        ("fietsverhuur", "bike rental", "de"),
        ("ov-fiets", "OV bike", "de"),
        ("deelfiets", "shared bike", "de"),
        ("scooter", "scooter", "de"),
        ("taxi", "taxi", "de"),
        ("uber", "Uber", "de"),
        ("blablacar", "BlaBlaCar", "de"),
        ("rit", "ride", "de"),
        ("reis", "journey", "de"),
        ("reisduur", "travel time", "de"),
        ("afstand", "distance", "de"),
        ("kilometer", "kilometre", "de"),
        ("reisschema", "travel schedule", "het"),
        ("reisplanner", "journey planner", "de"),
        ("9292", "9292", "de"),
        ("google maps", "Google Maps", "de"),
        ("navigatie", "navigation", "de"),
        ("gps", "GPS", "de"),
        ("verkeer", "traffic", "het"),
        ("file", "traffic jam", "de"),
        ("drukte", "crowding", "de"),
        ("spits", "rush hour", "de"),
        ("spitsuur", "peak hour", "het"),
        ("druk", "busy", None),
        ("rustig", "quiet", None),
        ("comfortabel", "comfortable", None),
        ("vol", "full", None),
        ("leeg", "empty", None),
        ("schoon", "clean", None),
        ("vies", "dirty", None),
        ("toegankelijk", "accessible", None),
        ("rolstoeltoegankelijk", "wheelchair accessible", None),
        ("toegankelijkheid", "accessibility", "de"),
        ("reistijd", "travel time", "de"),
        ("vertrekhal", "departure hall", "de"),
        ("aankomsthal", "arrival hall", "de"),
        ("bagageband", "baggage carousel", "de"),
        ("incheckbalie", "check-in desk", "de"),
        ("boardingpas", "boarding pass", "de"),
        ("gate", "gate", "de"),
        ("vlucht", "flight", "de"),
        ("treinverbinding", "train connection", "de"),
        ("overstapstation", "interchange station", "het"),
        ("spoorweg", "railway", "de"),
        ("metro", "metro", "de"),
        ("lightrail", "light rail", "de"),
        ("sneltram", "rapid tram", "de"),
        ("waterbus", "water bus", "de"),
        ("rondvaart", "canal cruise", "de"),
        ("toerist", "tourist", "de"),
        ("reiziger", "traveller", "de"),
        ("forens", "commuter", "de"),
        ("fietsroute", "cycle route", "de"),
        ("wandelroute", "walking route", "de"),
        ("autosnelweg", "motorway", "de"),
        ("provinciale weg", "provincial road", "de"),
        ("rijksweg", "national road", "de"),
        ("brug", "bridge", "de"),
        ("tunnel", "tunnel", "de"),
        ("viaduct", "viaduct", "het"),
        ("treinreiziger", "train passenger", "de"),
        ("busreiziger", "bus passenger", "de"),
        ("fietser", "cyclist", "de"),
        ("voetganger", "pedestrian", "de"),
        ("automobilist", "motorist", "de"),
        ("reizigersinformatie", "travel information", "de"),
        ("vertrekschema", "departure schedule", "het"),
        ("intercity", "intercity", "de"),
        ("sprinter", "sprinter", "de"),
        ("stoptrein", "stopping train", "de"),
        ("hogesnelheidstrein", "high-speed train", "de"),
        ("retour", "return", "de"),
        ("enkele reis", "single journey", "de"),
        ("dagkaart", "day ticket", "de"),
        ("weekkaart", "week ticket", "de"),
        ("maandkaart", "monthly ticket", "de"),
        ("jaarskaart", "annual ticket", "de"),
        ("korting", "discount", "de"),
        ("studentenkorting", "student discount", "de"),
        ("ouderenkorting", "senior discount", "de"),
        ("groepskaart", "group ticket", "de"),
        ("gezinsuitje", "family outing", "het"),
        ("dagje weg", "day out", "het"),
        ("weekendje", "weekend trip", "het"),
        ("stedentrip", "city trip", "de"),
        ("strandvakantie", "beach holiday", "de"),
        ("wintersport", "winter sports", "de"),
        ("camping", "camping", "de"),
        ("campingplaats", "campsite", "de"),
        ("vakantiepark", "holiday park", "het"),
        ("hotel", "hotel", "het"),
        ("b&b", "B&B", "de"),
        ("hostel", "hostel", "het"),
        ("reservering", "reservation", "de"),
        ("boeking", "booking", "de"),
        ("annulering", "cancellation", "de"),
        ("annuleringsvoorwaarden", "cancellation terms", "de"),
        ("inchecktijd", "check-in time", "de"),
        ("uitchecktijd", "check-out time", "de"),
        ("bagage", "luggage", "de"),
        ("handbagage", "hand luggage", "de"),
        ("ruimbagage", "hold luggage", "de"),
        ("bagage-allowance", "baggage allowance", "de"),
        ("overgewicht", "overweight", "het"),
        ("meerprijs", "surcharge", "de"),
        ("transfer", "transfer", "de"),
        ("shuttle", "shuttle", "de"),
        ("parkeerplaats", "parking", "de"),
        ("tankstation", "gas station", "het"),
        ("tolweg", "toll road", "de"),
        ("tol", "toll", "de"),
        ("vliegveld", "airport", "het"),
        ("luchthaven", "airport", "de"),
        ("vliegtuig", "airplane", "het"),
        ("vliegticket", "flight ticket", "het"),
        ("bagage-allowance", "baggage allowance", "de"),
        ("handbagage", "hand luggage", "de"),
        ("ruimbagage", "hold luggage", "de"),
        ("treinabonnement", "train subscription", "het"),
        ("daluren", "off-peak hours", "de"),
        ("spitsuren", "peak hours", "de"),
        ("reiskosten", "travel costs", "de"),
        ("kilometervergoeding", "mileage allowance", "de"),
        ("ov-abonnement", "public transport subscription", "het"),
        ("fietsvergoeding", "bike allowance", "de"),
        ("reiskostenvergoeding", "travel allowance", "de"),
        ("thuiswerkvergoeding", "home office allowance", "de"),
        ("onkostenvergoeding", "expense allowance", "de"),
        ("salarisonderhandeling", "salary negotiation", "de"),
        ("salarisverhoging", "pay rise", "de"),
        ("jaarsalaris", "annual salary", "het"),
        ("maandsalaris", "monthly salary", "het"),
        ("brutosalaris", "gross salary", "het"),
        ("netsalaris", "net salary", "het"),
        ("salarisstrook", "payslip", "de"),
        ("loonstrook", "payslip", "de"),
        ("jaaropgave", "annual statement", "de"),
        ("werkgeversverklaring", "employer statement", "de"),
        ("salarisverhoging", "pay rise", "de"),
        ("salarisonderhandeling", "salary negotiation", "de"),
        ("salarisindicatie", "salary indication", "de"),
        ("geldautomaten", "ATMs", "de"),
        ("bankfiliaal", "bank branch", "het"),
        ("spaarbedrag", "savings amount", "het"),
        ("geldovermaking", "money transfer", "de"),
        ("rente-op-rente", "compound interest", "de"),
        ("beleggingsplan", "investment plan", "het"),
        ("pensioenfonds", "pension fund", "het"),
        ("spaarrekening", "savings account", "de"),
        ("betaalrekening", "current account", "de"),
        ("zakgeld", "pocket money", "het"),
        ("kleedgeld", "clothing allowance", "het"),
        ("contant", "cash", None),
        ("pinnen", "to pay by card", None),
        ("overschrijven", "to transfer", None),
        ("incasso", "direct debit", "de"),
        ("tikkie", "Tikkie", "het"),
        ("betalingsverzoek", "payment request", "het"),
        ("ideal", "iDEAL", "de"),
    ],
    8: [  # Geld - 56 -> 150, need 94
        ("financiën", "finances", "de"),
        ("geldzaken", "financial affairs", "de"),
        ("financieel", "financial", None),
        ("geldelijk", "monetary", None),
        ("bedrag", "amount", "het"),
        ("som", "sum", "de"),
        ("totaal", "total", "het"),
        ("subtotaal", "subtotal", "het"),
        ("korting", "discount", "de"),
        ("btw", "VAT", "de"),
        ("belasting", "tax", "de"),
        ("belastingaangifte", "tax return", "de"),
        ("belastingdienst", "tax office", "de"),
        ("aanslag", "assessment", "de"),
        ("teruggave", "refund", "de"),
        ("voorheffing", "withholding", "de"),
        ("loonheffing", "wage tax", "de"),
        ("premie", "premium", "de"),
        ("zorgpremie", "health premium", "de"),
        ("eigen risico", "excess", "het"),
        ("verzekeraar", "insurer", "de"),
        ("polis", "policy", "de"),
        ("polisvoorwaarden", "policy terms", "de"),
        ("dekking", "coverage", "de"),
        ("verzekerd", "insured", None),
        ("onverzekerd", "uninsured", None),
        ("aansprakelijk", "liable", None),
        ("aansprakelijkheidsverzekering", "liability insurance", "de"),
        ("rechtsbijstand", "legal aid", "de"),
        ("rechtsbijstandverzekering", "legal expenses insurance", "de"),
        ("reisverzekering", "travel insurance", "de"),
        ("annulering", "cancellation", "de"),
        ("annuleringsverzekering", "cancellation insurance", "de"),
        ("spaarpot", "piggy bank", "de"),
        ("spaargeld", "savings", "het"),
        ("spaardoel", "savings goal", "het"),
        ("budgetteren", "to budget", None),
        ("uitgaven bijhouden", "to track expenses", None),
        ("huishoudboekje", "household budget", "het"),
        ("excel", "Excel", "de"),
        ("app", "app", "de"),
        ("geld-app", "money app", "de"),
        ("ideal", "iDEAL", "de"),
        ("paypal", "PayPal", "de"),
        ("creditcard", "credit card", "de"),
        ("pinpas", "debit card", "de"),
        ("paspoort", "passport", "het"),
        ("pincode", "PIN code", "de"),
        ("geheim", "secret", "het"),
        ("fraude", "fraud", "de"),
        ("oplichting", "scam", "de"),
        ("phishing", "phishing", "de"),
        ("waarschuwing", "warning", "de"),
        ("voorzichtig", "careful", None),
        ("veilig", "safe", None),
        ("onveilig", "unsafe", None),
        ("encryptie", "encryption", "de"),
        ("tweefactorauthenticatie", "two-factor authentication", "de"),
        ("2fa", "2FA", "de"),
        ("lening", "loan", "de"),
        ("hypotheek", "mortgage", "de"),
        ("rente", "interest", "de"),
        ("rentepercentage", "interest rate", "het"),
        ("aflossing", "repayment", "de"),
        ("maandlasten", "monthly payments", "de"),
        ("schuld", "debt", "de"),
        ("schulden", "debts", "de"),
        ("schuldsanering", "debt restructuring", "de"),
        ("betalingsregeling", "payment plan", "de"),
        ("incassobureau", "collection agency", "het"),
        ("deurwaarder", "bailiff", "de"),
        ("beslag", "seizure", "het"),
        ("faillissement", "bankruptcy", "het"),
        ("geldautomaten", "ATMs", "de"),
        ("bankfiliaal", "bank branch", "het"),
        ("online bankieren", "online banking", "het"),
        ("mobiel bankieren", "mobile banking", "het"),
        ("betaalverzoek", "payment request", "het"),
        ("periodieke betaling", "recurring payment", "de"),
        ("machtiging", "authorization", "de"),
        ("automatische incasso", "direct debit", "de"),
        ("acceptgiro", "giro transfer", "de"),
        ("overschrijving", "transfer", "de"),
        ("beschikbaar saldo", "available balance", "het"),
        ("kredietlimiet", "credit limit", "de"),
        ("maandelijkse lasten", "monthly expenses", "de"),
        ("vaste lasten", "fixed costs", "de"),
        ("variabele lasten", "variable costs", "de"),
        ("pinbetaling", "card payment", "de"),
        ("contactloos betalen", "contactless payment", "het"),
        ("mobiel betalen", "mobile payment", "het"),
        ("bankpas", "bank card", "de"),
        ("creditcard", "credit card", "de"),
        ("betaalpas", "payment card", "de"),
        ("daglimiet", "daily limit", "de"),
        ("opnamelimiet", "withdrawal limit", "de"),
        ("spaardoel", "savings goal", "het"),
        ("belegging", "investment", "de"),
        ("spaarrente", "savings interest", "de"),
        ("rentepercentage", "interest rate", "het"),
        ("jaarrente", "annual interest", "de"),
        ("maandrente", "monthly interest", "de"),
        ("geldopname", "withdrawal", "de"),
        ("storting", "deposit", "de"),
        ("betalingsherinnering", "payment reminder", "de"),
        ("incassokosten", "collection costs", "de"),
        ("boeterente", "penalty interest", "de"),
        ("spaarplan", "savings plan", "het"),
        ("termijndeposito", "term deposit", "het"),
        ("spaarrekeningrente", "savings account interest", "de"),
        ("consumptief krediet", "consumer credit", "het"),
        ("doorlopend krediet", "revolving credit", "het"),
        ("persoonlijke lening", "personal loan", "de"),
        ("consumptief lenen", "consumer lending", "het"),
        ("hypotheekadviseur", "mortgage adviser", "de"),
        ("financieel adviseur", "financial adviser", "de"),
        ("geldautomaat", "ATM", "de"),
        ("spaarbedrag", "savings amount", "het"),
        ("geldovermaking", "money transfer", "de"),
        ("rente-op-rente", "compound interest", "de"),
        ("beleggingsplan", "investment plan", "het"),
        ("pensioenfonds", "pension fund", "het"),
        ("claim", "claim", "de"),
        ("ziektekosten", "healthcare costs", "de"),
        ("eigen bijdrage", "own contribution", "de"),
        ("verzekeringspremie", "insurance premium", "de"),
        ("jaarpremie", "annual premium", "de"),
        ("maandpremie", "monthly premium", "de"),
        ("verzekerd bedrag", "insured amount", "het"),
        ("pensioenleeftijd", "retirement age", "de"),
        ("vut", "early retirement", "de"),
        ("prepensioen", "early retirement", "het"),
        ("pensioenregeling", "pension scheme", "de"),
        ("werkgeversbijdrage", "employer contribution", "de"),
        ("werknemersbijdrage", "employee contribution", "de"),
        ("vermogen", "assets", "het"),
        ("bezittingen", "possessions", "de"),
        ("spaartegoed", "savings balance", "het"),
        ("beleggingsportefeuille", "investment portfolio", "de"),
        ("aandelen", "shares", "de"),
        ("obligaties", "bonds", "de"),
        ("indexfonds", "index fund", "het"),
        ("beleggingsfonds", "investment fund", "het"),
        ("dividend", "dividend", "het"),
        ("koers", "rate", "de"),
        ("koerswinst", "capital gain", "de"),
        ("verlies", "loss", "het"),
        ("winst", "profit", "de"),
        ("belastingvrij", "tax-free", None),
        ("fiscaal", "fiscal", None),
        ("voorlopige aanslag", "provisional assessment", "de"),
        ("definitieve aanslag", "final assessment", "de"),
        ("bezwaarschrift", "objection", "het"),
        ("belastingadviseur", "tax adviser", "de"),
        ("accountant", "accountant", "de"),
        ("boekhouder", "bookkeeper", "de"),
        ("jaarrekening", "annual accounts", "de"),
        ("balans", "balance sheet", "de"),
        ("winst-en-verliesrekening", "profit and loss", "de"),
        ("kasstroom", "cash flow", "de"),
        ("omzet", "revenue", "de"),
        ("kosten", "costs", "de"),
        ("winstmarge", "profit margin", "de"),
        ("resultaat", "result", "het"),
        ("winst", "profit", "de"),
        ("verlies", "loss", "het"),
        ("afschrijving", "depreciation", "de"),
        ("balans", "balance sheet", "de"),
        ("jaarrekening", "annual accounts", "de"),
        ("winst-en-verliesrekening", "profit and loss", "de"),
        ("kasstroom", "cash flow", "de"),
        ("omzet", "revenue", "de"),
        ("kosten", "costs", "de"),
        ("resultaat", "result", "het"),
        ("winst", "profit", "de"),
        ("verlies", "loss", "het"),
        ("winstmarge", "profit margin", "de"),
        ("omzet", "revenue", "de"),
        ("resultaat", "result", "het"),
        ("winst", "profit", "de"),
        ("verlies", "loss", "het"),
        ("winstmarge", "profit margin", "de"),
        ("afschrijving", "depreciation", "de"),
        ("jaarrekening", "annual accounts", "de"),
        ("balans", "balance sheet", "de"),
        ("winst-en-verliesrekening", "profit and loss", "de"),
        ("kasstroom", "cash flow", "de"),
        ("omzet", "revenue", "de"),
        ("kosten", "costs", "de"),
        ("historische figuur", "historical figure", "de"),
        ("tijdperk", "era", "het"),
        ("eeuw", "century", "de"),
        ("decennium", "decade", "het"),
        ("generatie", "generation", "de"),
        ("archeoloog", "archaeologist", "de"),
        ("archeologische vondst", "archaeological find", "de"),
        ("opgraving", "excavation", "de"),
        ("museum", "museum", "het"),
        ("tentoonstelling", "exhibition", "de"),
        ("rondleiding", "tour", "de"),
        ("gids", "guide", "de"),
        ("erfgoed", "heritage", "het"),
        ("monument", "monument", "het"),
        ("restauratie", "restoration", "de"),
        ("archeologie", "archaeology", "de"),
        ("tijdlijn", "timeline", "de"),
        ("chronologie", "chronology", "de"),
        ("historische bron", "historical source", "de"),
        ("archief", "archive", "het"),
        ("document", "document", "het"),
        ("handschrift", "manuscript", "het"),
        ("kaart", "map", "de"),
        ("historische kaart", "historical map", "de"),
        ("middeleeuwse stad", "medieval town", "de"),
        ("romeinse tijd", "Roman period", "de"),
        ("gouden eeuw", "Golden Age", "de"),
        ("industriële revolutie", "industrial revolution", "de"),
        ("tachtigjarige oorlog", "Eighty Years' War", "de"),
        ("voc", "VOC", "de"),
        ("kolonialisme", "colonialism", "het"),
        ("slavernij", "slavery", "de"),
        ("afschaffing", "abolition", "de"),
        ("stadsarchief", "city archive", "het"),
        ("rijksarchief", "national archive", "het"),
        ("stadsarchivaris", "city archivist", "de"),
        ("historisch archief", "historical archive", "het"),
        ("archiefstuk", "archive document", "het"),
        ("bronnenpublicatie", "source publication", "de"),
        ("historische roman", "historical novel", "de"),
        ("geschiedenisboek", "history book", "het"),
        ("geschiedenisdocent", "history teacher", "de"),
        ("geschiedenisles", "history lesson", "de"),
        ("geschiedenisvak", "history subject", "het"),
        ("geschiedenisonderwijs", "history education", "het"),
        ("geschiedenisstudent", "history student", "de"),
        ("geschiedenisprofessor", "history professor", "de"),
        ("geschiedeniswetenschap", "history science", "de"),
        ("geschiedenisonderzoek", "history research", "het"),
        ("geschiedenisverhaal", "history story", "het"),
        ("geschiedenisvereniging", "history society", "de"),
    ],
    9: [  # Geschiedenis - 49 -> 200, need 151
        ("geschiedenisles", "history lesson", "de"),
        ("geschiedenisvak", "history subject", "het"),
        ("geschiedenisonderwijs", "history education", "het"),
        ("geschiedenisstudent", "history student", "de"),
        ("geschiedenisprofessor", "history professor", "de"),
        ("geschiedeniswetenschap", "historical science", "de"),
        ("geschiedenisonderzoek", "historical research", "het"),
        ("stadsarchief", "city archive", "het"),
        ("rijksarchief", "national archive", "het"),
        ("chronologie", "chronology", "de"),
        ("tijdperk", "era", "het"),
        ("periode", "period", "de"),
        ("tijdvak", "period", "het"),
        ("oudheid", "antiquity", "de"),
        ("middeleeuwen", "Middle Ages", "de"),
        ("renaissance", "Renaissance", "de"),
        ("verlichting", "Enlightenment", "de"),
        ("moderne tijd", "modern era", "de"),
        ("contemporain", "contemporary", None),
        ("prehistorie", "prehistory", "de"),
        ("steentijd", "Stone Age", "de"),
        ("ijzertijd", "Iron Age", "de"),
        ("romeinen", "Romans", "de"),
        ("romeins", "Roman", None),
        ("germanen", "Germanic tribes", "de"),
        ("vikingen", "Vikings", "de"),
        ("ridders", "knights", "de"),
        ("kastelen", "castles", "de"),
        ("kathedralen", "cathedrals", "de"),
        ("reformatie", "Reformation", "de"),
        ("tachtigjarige oorlog", "Eighty Years' War", "de"),
        ("gouden eeuw", "Golden Age", "de"),
        ("voc", "VOC", "de"),
        ("kolonialisme", "colonialism", "het"),
        ("slavernij", "slavery", "de"),
        ("afschaffing", "abolition", "de"),
        ("industrialisatie", "industrialization", "de"),
        ("eerste wereldoorlog", "First World War", "de"),
        ("tweede wereldoorlog", "Second World War", "de"),
        ("holocaust", "Holocaust", "de"),
        ("bezetting", "occupation", "de"),
        ("verzet", "resistance", "het"),
        ("verzetsstrijder", "resistance fighter", "de"),
        ("bevrijding", "liberation", "de"),
        ("wederopbouw", "reconstruction", "de"),
        ("jaren zestig", "sixties", "de"),
        ("protest", "protest", "het"),
        ("emancipatie", "emancipation", "de"),
        ("vrouwenemancipatie", "women's liberation", "de"),
        ("kinderbijslag", "child benefit", "de"),
        ("welvaartstaat", "welfare state", "de"),
        ("europese unie", "European Union", "de"),
        ("samenwerking", "cooperation", "de"),
        ("vredesbeweging", "peace movement", "de"),
        ("milieu", "environment", "het"),
        ("klimaat", "climate", "het"),
        ("duurzaamheid", "sustainability", "de"),
        ("immigratie", "immigration", "de"),
        ("multiculturalisme", "multiculturalism", "het"),
        ("integratie", "integration", "de"),
        ("geschiedschrijving", "historiography", "de"),
        ("historicus", "historian", "de"),
        ("bronnenonderzoek", "source research", "het"),
        ("primaire bron", "primary source", "de"),
        ("secundaire bron", "secondary source", "de"),
        ("oral history", "oral history", "de"),
        ("getuigenis", "testimony", "de"),
        ("ooggetuige", "eyewitness", "de"),
        ("overlever", "survivor", "de"),
        ("herdenking", "commemoration", "de"),
        ("dodenherdenking", "Remembrance Day", "de"),
        ("bevrijdingsdag", "Liberation Day", "de"),
        ("vlag", "flag", "de"),
        ("halfstok", "half-mast", None),
        ("twee minuten stilte", "two minutes silence", "de"),
        ("krans", "wreath", "de"),
        ("monument", "monument", "het"),
        ("standbeeld", "statue", "het"),
        ("plaquette", "plaque", "de"),
        ("gedenksteen", "memorial stone", "de"),
        ("herinneringscentrum", "memorial centre", "het"),
        ("kamp", "camp", "het"),
        ("concentratiekamp", "concentration camp", "het"),
        ("anne frank", "Anne Frank", "de"),
        ("dagboek", "diary", "het"),
        ("wereldoorlog", "world war", "de"),
        ("vredesverdrag", "peace treaty", "het"),
        ("revolutie", "revolution", "de"),
        ("opstand", "uprising", "de"),
        ("onafhankelijkheid", "independence", "de"),
        ("democratisering", "democratization", "de"),
        ("technologische vooruitgang", "technological progress", "de"),
        ("uitvinding", "invention", "de"),
        ("ontdekking", "discovery", "de"),
        ("expeditie", "expedition", "de"),
        ("ontdekkingsreiziger", "explorer", "de"),
        ("handelsroute", "trade route", "de"),
        ("specerijen", "spices", "de"),
        ("slavenhandel", "slave trade", "de"),
        ("koloniaal verleden", "colonial past", "het"),
        ("dekolonisatie", "decolonization", "de"),
        ("handelscompagnie", "trading company", "de"),
        ("abolitionisme", "abolitionism", "het"),
        ("vaderlandse geschiedenis", "national history", "de"),
        ("wereldgeschiedenis", "world history", "de"),
        ("tijdsgeest", "spirit of the times", "de"),
        ("historische context", "historical context", "de"),
        ("geschiedkundige", "historian", "de"),
        ("bronnenkritiek", "source criticism", "de"),
        ("historisch besef", "historical awareness", "het"),
        ("verlichtingsdenkers", "Enlightenment thinkers", "de"),
        ("verzuiling", "pillarization", "de"),
        ("staten-generaal", "States General", "de"),
        ("grondwet", "constitution", "de"),
        ("grondwetsherziening", "constitutional revision", "de"),
        ("stadhouders", "stadholders", "de"),
        ("republiek der zeven verenigde nederlanden", "Dutch Republic", "de"),
        ("bataven", "Batavians", "de"),
        ("romeinse tijd", "Roman period", "de"),
        ("middeleeuwse stad", "medieval town", "de"),
        ("gracht", "canal", "de"),
        ("vestingstad", "fortified town", "de"),
        ("handelsstad", "trading city", "de"),
        ("havenstad", "port city", "de"),
        ("stadsmuur", "city wall", "de"),
        ("poort", "gate", "de"),
        ("toren", "tower", "de"),
        ("kerk", "church", "de"),
        ("abdij", "abbey", "de"),
        ("klooster", "monastery", "het"),
        ("burcht", "fortress", "de"),
        ("citadel", "citadel", "de"),
        ("arsenaal", "arsenal", "het"),
        ("wapen", "weapon", "het"),
        ("kanon", "cannon", "het"),
        ("oorlogsschip", "warship", "het"),
        ("handelsvloot", "merchant fleet", "de"),
        ("zeemacht", "navy", "de"),
        ("leger", "army", "het"),
        ("soldaat", "soldier", "de"),
        ("generaal", "general", "de"),
        ("admiraal", "admiral", "de"),
        ("vorst", "monarch", "de"),
        ("vorstin", "monarch", "de"),
        ("troon", "throne", "de"),
        ("kroon", "crown", "de"),
        ("scepter", "sceptre", "de"),
        ("troonswisseling", "succession", "de"),
        ("dynastie", "dynasty", "de"),
        ("koningshuis", "royal house", "het"),
        ("hof", "court", "het"),
        ("hofhouding", "court", "de"),
        ("edelman", "nobleman", "de"),
        ("ridder", "knight", "de"),
        ("vazal", "vassal", "de"),
        ("feodalisme", "feudalism", "het"),
        ("leen", "fief", "het"),
        ("leenheer", "liege lord", "de"),
        ("leenman", "vassal", "de"),
        ("gilde", "guild", "het"),
        ("ambacht", "craft", "het"),
        ("handwerksman", "craftsman", "de"),
        ("koopman", "merchant", "de"),
        ("handelaar", "trader", "de"),
        ("markt", "market", "de"),
        ("jaarmarkt", "fair", "de"),
        ("beurs", "exchange", "de"),
        ("effectenbeurs", "stock exchange", "de"),
        ("handelsverdrag", "trade treaty", "het"),
    ],
    10: [  # Samen leven - 58 -> 150, need 92
        ("samenleving", "society", "de"),
        ("gemeenschap", "community", "de"),
        ("buurt", "neighbourhood", "de"),
        ("wijk", "district", "de"),
        ("stad", "city", "de"),
        ("dorp", "village", "het"),
        ("provincie", "province", "de"),
        ("land", "country", "het"),
        ("burger", "citizen", "de"),
        ("inwoner", "inhabitant", "de"),
        ("medeburger", "fellow citizen", "de"),
        ("buren", "neighbours", "de"),
        ("buurtschap", "neighbourliness", "de"),
        ("straat", "street", "de"),
        ("blok", "block", "het"),
        ("flat", "apartment building", "de"),
        ("woningbouwvereniging", "housing association", "de"),
        ("vve", "homeowners association", "de"),
        ("huurdersvereniging", "tenants association", "de"),
        ("actiegroep", "action group", "de"),
        ("bewonerscommissie", "residents committee", "de"),
        ("wijkraad", "district council", "de"),
        ("gemeenteraad", "municipal council", "de"),
        ("democratie", "democracy", "de"),
        ("dictatuur", "dictatorship", "de"),
        ("vrijheid", "freedom", "de"),
        ("gelijkheid", "equality", "de"),
        ("rechtvaardigheid", "justice", "de"),
        ("solidariteit", "solidarity", "de"),
        ("participatie", "participation", "de"),
        ("burgerparticipatie", "citizen participation", "de"),
        ("referendum", "referendum", "het"),
        ("petitie", "petition", "de"),
        ("demonstratie", "demonstration", "de"),
        ("protest", "protest", "het"),
        ("staking", "strike", "de"),
        ("vakbond", "trade union", "de"),
        ("werkgeversorganisatie", "employers organization", "de"),
        ("belangenvereniging", "interest group", "de"),
        ("ngo", "NGO", "de"),
        ("goede doel", "charity", "het"),
        ("doneren", "to donate", None),
        ("vrijwilligerswerk", "volunteer work", "het"),
        ("mantelzorg", "informal care", "de"),
        ("zorg", "care", "de"),
        ("ouderenzorg", "elderly care", "de"),
        ("gehandicaptenzorg", "disability care", "de"),
        ("jeugdzorg", "youth care", "de"),
        ("geestelijke gezondheidszorg", "mental health care", "de"),
        ("thuiszorg", "home care", "de"),
        ("verpleeghuis", "nursing home", "het"),
        ("bejaardentehuis", "old people's home", "het"),
        ("kinderopvang", "childcare", "de"),
        ("peuterspeelzaal", "playgroup", "de"),
        ("sportvereniging", "sports club", "de"),
        ("muziekvereniging", "music society", "de"),
        ("theatergroep", "theatre group", "de"),
        ("leeskring", "book club", "de"),
        ("hobbyclub", "hobby club", "de"),
        ("ontmoetingsplek", "meeting place", "de"),
        ("buurthuis", "community centre", "het"),
        ("bibliotheek", "library", "de"),
        ("cultureel centrum", "cultural centre", "het"),
        ("sportcomplex", "sports complex", "het"),
        ("speeltuin", "playground", "de"),
        ("park", "park", "het"),
        ("groen", "green space", "het"),
        ("openbare ruimte", "public space", "de"),
        ("veiligheid", "safety", "de"),
        ("leefbaarheid", "livability", "de"),
        ("overlast", "nuisance", "de"),
        ("geluidsoverlast", "noise nuisance", "de"),
        ("burenruzie", "neighbour dispute", "de"),
        ("bemiddeling", "mediation", "de"),
        ("conflict", "conflict", "het"),
        ("oplossing", "solution", "de"),
        ("buurtfeest", "street party", "het"),
        ("straatfeest", "street festival", "het"),
        ("buurtbarbecue", "neighbourhood barbecue", "de"),
        ("open dag", "open day", "de"),
        ("inloop", "drop-in", "de"),
        ("activiteit", "activity", "de"),
        ("evenement", "event", "het"),
        ("festival", "festival", "het"),
        ("markt", "market", "de"),
        ("weekmarkt", "weekly market", "de"),
        ("kerstmarkt", "Christmas market", "de"),
        ("rommelmarkt", "flea market", "de"),
        ("gezamenlijk", "joint", None),
        ("collectief", "collective", None),
        ("samenhorigheid", "solidarity", "de"),
        ("verbondenheid", "connectedness", "de"),
        ("wederzijdse hulp", "mutual aid", "de"),
        ("burenhulp", "neighbour help", "de"),
        ("buurtinitiatief", "neighbourhood initiative", "het"),
        ("wijkagent", "community police officer", "de"),
        ("buurtpreventie", "neighbourhood watch", "de"),
        ("buurtapp", "neighbourhood app", "de"),
        ("buurtwhatsapp", "neighbourhood WhatsApp", "de"),
        ("buurtbbq", "neighbourhood BBQ", "de"),
        ("gezamenlijke tuin", "shared garden", "de"),
        ("speeltuinvereniging", "playground association", "de"),
        ("buurtbudget", "neighbourhood budget", "het"),
        ("participatiebudget", "participation budget", "het"),
        ("bewonersavond", "residents evening", "de"),
        ("wijkbijeenkomst", "district meeting", "de"),
        ("buurtondersteuning", "neighbourhood support", "de"),
        ("mantelzorgondersteuning", "informal care support", "de"),
        ("vrijwilligerscentrale", "volunteer centre", "de"),
        ("buurtcontact", "neighbourhood contact", "het"),
        ("buurtgenoot", "neighbour", "de"),
        ("straatgenoot", "neighbour", "de"),
        ("straatfeest", "street party", "het"),
        ("buurtvereniging", "neighbourhood association", "de"),
        ("wijkvereniging", "district association", "de"),
        ("buurtcomité", "neighbourhood committee", "het"),
        ("buurtbemiddeling", "neighbourhood mediation", "de"),
        ("buurtvraag", "neighbourhood question", "de"),
        ("buurtonderzoek", "neighbourhood survey", "het"),
        ("buurtplan", "neighbourhood plan", "het"),
        ("wijkplan", "district plan", "het"),
        ("leefomgeving", "living environment", "de"),
        ("woonomgeving", "residential environment", "de"),
        ("stadsvernieuwing", "urban renewal", "de"),
        ("wijkvernieuwing", "district renewal", "de"),
        ("woningbouw", "housing", "de"),
        ("sociale woningbouw", "social housing", "de"),
        ("huurwoning", "rental home", "de"),
        ("koopwoning", "owner-occupied home", "de"),
        ("woningcorporatie", "housing association", "de"),
        ("huurdersvereniging", "tenants association", "de"),
        ("huurdersbelang", "tenant interest", "het"),
        ("huurdersraad", "tenants council", "de"),
        ("huurdersvereniging", "tenants association", "de"),
        ("huurdersbelang", "tenant interest", "het"),
        ("medezeggenschap", "participation", "de"),
        ("inspraak", "consultation", "de"),
        ("burgerparticipatie", "citizen participation", "de"),
        ("referendum", "referendum", "het"),
        ("petitie", "petition", "de"),
        ("handtekeningenactie", "signature campaign", "de"),
        ("protestactie", "protest action", "de"),
        ("demonstratie", "demonstration", "de"),
        ("protestmars", "protest march", "de"),
        ("sit-in", "sit-in", "de"),
        ("staking", "strike", "de"),
        ("vakbond", "trade union", "de"),
        ("werkgeversorganisatie", "employers organization", "de"),
        ("belangenvereniging", "interest group", "de"),
        ("ngo", "NGO", "de"),
        ("goede doel", "charity", "het"),
        ("doneren", "to donate", None),
        ("vrijwilligerswerk", "volunteer work", "het"),
        ("mantelzorg", "informal care", "de"),
        ("zorg", "care", "de"),
        ("ouderenzorg", "elderly care", "de"),
        ("gehandicaptenzorg", "disability care", "de"),
        ("jeugdzorg", "youth care", "de"),
        ("geestelijke gezondheidszorg", "mental health care", "de"),
        ("thuiszorg", "home care", "de"),
        ("verpleeghuis", "nursing home", "het"),
        ("bejaardentehuis", "old people's home", "het"),
        ("buurtwinkel", "neighbourhood shop", "de"),
        ("buurtsuper", "neighbourhood supermarket", "de"),
        ("buurtcentrum", "community centre", "het"),
        ("wijkcentrum", "district centre", "het"),
        ("buurtmaaltijd", "community meal", "de"),
        ("buurtontmoeting", "neighbourhood meeting", "de"),
        ("buurtcafé", "neighbourhood café", "het"),
        ("buurtkrant", "neighbourhood newspaper", "de"),
        ("wijkkrant", "district newspaper", "de"),
        ("buurtnieuws", "neighbourhood news", "het"),
        ("buurtagenda", "neighbourhood agenda", "de"),
        ("buurtkalender", "neighbourhood calendar", "de"),
        ("buurtactiviteit", "neighbourhood activity", "de"),
        ("buurtproject", "neighbourhood project", "het"),
        ("buurtverbetering", "neighbourhood improvement", "de"),
        ("buurtveiligheid", "neighbourhood safety", "de"),
        ("buurttoezicht", "neighbourhood surveillance", "het"),
        ("buurtwacht", "neighbourhood watch", "de"),
        ("buurtfeestje", "neighbourhood party", "het"),
        ("straatfeestje", "street party", "het"),
        ("buurtrestaurant", "neighbourhood restaurant", "het"),
        ("buurtbakker", "neighbourhood baker", "de"),
        ("buurtslager", "neighbourhood butcher", "de"),
        ("buurtapotheek", "neighbourhood pharmacy", "de"),
        ("buurtarts", "neighbourhood doctor", "de"),
        ("buurthuis", "community centre", "het"),
        ("buurtwerk", "community work", "het"),
        ("buurtopbouw", "community building", "de"),
        ("buurtcohesie", "community cohesion", "de"),
        ("buurtidentiteit", "neighbourhood identity", "de"),
        ("buurtgevoel", "neighbourhood feeling", "het"),
    ],
}


def main():
    with open(WINDMEE_PATH) as f:
        data = json.load(f)

    # First: remove duplicates (keep first occurrence per theme)
    seen_by_theme = {}
    deduped = []
    for v in data["vocab"]:
        t = v["theme"]
        key = v["nl"].lower().strip()
        if t not in seen_by_theme:
            seen_by_theme[t] = set()
        if key in seen_by_theme[t]:
            continue
        seen_by_theme[t].add(key)
        deduped.append(v)

    # Build by theme
    existing_by_theme = {}
    for v in deduped:
        t = v["theme"]
        if t not in existing_by_theme:
            existing_by_theme[t] = []
        existing_by_theme[t].append(v)

    # Global dedup: keep each word only in first theme where it appears
    seen_global = set()
    new_vocab = []
    for theme_id in range(1, 11):
        existing = existing_by_theme.get(theme_id, [])
        theme_words = set()
        for v in existing:
            key = v["nl"].lower().strip()
            if key not in seen_global:
                new_vocab.append(v)
                seen_global.add(key)
                theme_words.add(key)
        needed = max(0, MIN_PER_THEME - len(theme_words))

        if theme_id in EXTRA_VOCAB and needed > 0:
            max_id = max(
                (int(v["id"].split("_")[1]) for v in existing),
                default=-1,
            )
            added = 0
            for nl, en, article in EXTRA_VOCAB[theme_id]:
                if added >= needed:
                    break
                key = nl.lower().strip()
                if key in theme_words or key in seen_global:
                    continue
                max_id += 1
                new_vocab.append({
                    "id": f"w{theme_id:02d}_{max_id:04d}",
                    "theme": theme_id,
                    "nl": nl,
                    "article": article,
                    "en": en,
                    "tags": [],
                })
                theme_words.add(key)
                seen_global.add(key)
                added += 1

    new_vocab.sort(key=lambda v: (v["theme"], v["id"]))
    data["vocab"] = new_vocab

    with open(WINDMEE_PATH, "w") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    from collections import Counter
    counts = Counter(v["theme"] for v in data["vocab"])
    print("Wind mee theme counts (min 200):")
    for t in sorted(counts.keys()):
        status = "✓" if counts[t] >= MIN_PER_THEME else "✗"
        print(f"  Theme {t}: {counts[t]} {status}")
    print(f"Total: {len(data['vocab'])} words")

    # Check for duplicates
    for t in range(1, 11):
        words = [v["nl"].lower() for v in data["vocab"] if v["theme"] == t]
        dups = [w for w in words if words.count(w) > 1]
        if dups:
            print(f"  WARNING: Duplicates in theme {t}: {set(dups)}")


if __name__ == "__main__":
    main()
