#!/usr/bin/env python3
"""Expand all Wind mee themes with comprehensive vocabulary (Wonen-style)."""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
WINDMEE_PATH = ROOT / "apps" / "web" / "public" / "content" / "windmee.json"

# Format: (nl, en, article) - article: "de", "het", or None
EXPANSIONS = {
    2: [  # Sociale contacten - telephoning, appointments, joy/sorrow
        ("telefoon", "phone", "de"),
        ("mobiel", "mobile", "de"),
        ("sms", "text message", "de"),
        ("whatsapp", "WhatsApp", "de"),
        ("oproep", "call", "de"),
        ("voicemail", "voicemail", "de"),
        ("agenda", "agenda", "de"),
        ("kalender", "calendar", "de"),
        ("datum", "date", "de"),
        ("tijdstip", "time", "het"),
        ("locatie", "location", "de"),
        ("uitnodiging", "invitation", "de"),
        ("verjaardagsfeest", "birthday party", "het"),
        ("huwelijk", "wedding", "het"),
        ("begrafenis", "funeral", "de"),
        ("condoleance", "condolence", "de"),
        ("gefeliciteerd", "congratulations", None),
        ("beterschap", "get well soon", None),
        ("succes", "success", "het"),
        ("geluk", "happiness", "het"),
        ("verdriet", "sadness", "het"),
        ("emotie", "emotion", "de"),
        ("reactie", "reaction", "de"),
        ("reageren", "to react", None),
        ("telefoneren", "to phone", None),
        ("een bericht achterlaten", "to leave a message", None),
        ("terugbellen", "to call back", None),
        ("afzeggen", "to cancel", None),
        ("bevestigen", "to confirm", None),
        ("uitnodigen", "to invite", None),
        ("dankbaar", "grateful", None),
        ("trots", "proud", None),
        ("bezorgd", "worried", None),
        ("geschokt", "shocked", None),
        ("verrast", "surprised", None),
        ("ontroerd", "moved", None),
        ("medeleven", "compassion", "het"),
        ("steun", "support", "de"),
        ("troost", "comfort", "de"),
        ("aanmoediging", "encouragement", "de"),
        ("compliment", "compliment", "het"),
        ("kaartje", "card", "het"),
        ("bloemen", "flowers", "de"),
        ("cadeau", "present", "het"),
        ("feest vieren", "to celebrate", None),
        ("een kaartje sturen", "to send a card", None),
        ("opbellen", "to call up", None),
        ("een afspraak maken", "to make an appointment", None),
        ("afzeggen", "to cancel", None),
        ("verzetten", "to reschedule", None),
        ("deelname", "participation", "de"),
        ("aanwezigheid", "attendance", "de"),
        ("afwezigheid", "absence", "de"),
        ("gezellig", "cozy", None),
        ("geanimeerd", "animated", None),
        ("formele brief", "formal letter", "de"),
        ("informeel", "informal", None),
    ],
    3: [  # Onderwijs - caregivers 0-4, school 4-12, subjects 12-18, further education
        ("kinderopvang", "childcare", "de"),
        ("crèche", "nursery", "de"),
        ("peuter", "toddler", "de"),
        ("baby", "baby", "de"),
        ("oppassen", "to babysit", None),
        ("voeden", "to feed", None),
        ("verschonen", "to change", None),
        ("basisschool", "primary school", "de"),
        ("middelbare school", "secondary school", "de"),
        ("universiteit", "university", "de"),
        ("hogeschool", "university of applied sciences", "de"),
        ("mbo", "vocational education", "het"),
        ("havo", "HAVO", "de"),
        ("vwo", "VWO", "het"),
        ("vmbo", "VMBO", "het"),
        ("Nederlands", "Dutch", "het"),
        ("wiskunde", "mathematics", "de"),
        ("Engels", "English", "het"),
        ("geschiedenis", "history", "de"),
        ("aardrijkskunde", "geography", "de"),
        ("natuurkunde", "physics", "de"),
        ("scheikunde", "chemistry", "de"),
        ("biologie", "biology", "de"),
        ("gym", "PE", "de"),
        ("tekenen", "art", "het"),
        ("muziek", "music", "de"),
        ("klas", "class", "de"),
        ("schooljaar", "school year", "het"),
        ("rapport", "report", "het"),
        ("cijfer", "grade", "het"),
        ("tentamen", "exam", "het"),
        ("slaag", "pass", "de"),
        ("zak", "fail", "de"),
        ("studeren", "to study", None),
        ("leren", "to learn", None),
        ("onderwijzen", "to teach", None),
        ("opleiden", "to train", None),
        ("stage lopen", "to do an internship", None),
        ("afstuderen", "to graduate", None),
        ("bachelor", "bachelor", "de"),
        ("master", "master", "de"),
        ("scriptie", "thesis", "de"),
        ("college", "lecture", "het"),
        ("werkcollege", "tutorial", "het"),
        ("bibliotheek", "library", "de"),
        ("studie", "study", "de"),
        ("opleiding", "education", "de"),
        ("cursus", "course", "de"),
        ("cursist", "course participant", "de"),
        ("schooltas", "school bag", "de"),
        ("schrift", "notebook", "het"),
        ("pen", "pen", "de"),
        ("potlood", "pencil", "het"),
        ("gum", "eraser", "de"),
        ("rekenmachine", "calculator", "de"),
        ("bord", "board", "het"),
        ("krijt", "chalk", "het"),
        ("project", "project", "het"),
        ("presentatie", "presentation", "de"),
        ("spreekbeurt", "oral presentation", "de"),
        ("excursie", "excursion", "de"),
        ("schoolreis", "school trip", "de"),
        ("ouderavond", "parents' evening", "de"),
        ("mentor", "mentor", "de"),
        ("decanaat", "careers office", "het"),
        ("spreekvaardigheid", "speaking skill", "de"),
        ("schrijfvaardigheid", "writing skill", "de"),
        ("luistervaardigheid", "listening skill", "de"),
        ("leesvaardigheid", "reading skill", "de"),
        ("niveau", "level", "het"),
        ("certificaat", "certificate", "het"),
    ],
    4: [  # Werk zoeken - sectors, traits, vacancies, CV, internship, cover letter, interview
        ("beroep", "profession", "het"),
        ("functie", "position", "de"),
        ("fulltime", "full-time", None),
        ("parttime", "part-time", None),
        ("flexibel", "flexible", None),
        ("vast", "permanent", None),
        ("tijdelijk", "temporary", None),
        ("uurtarief", "hourly rate", "het"),
        ("bruto", "gross", None),
        ("netto", "net", None),
        ("zorgsector", "healthcare sector", "de"),
        ("onderwijssector", "education sector", "de"),
        ("techniek", "engineering", "de"),
        ("handel", "trade", "de"),
        ("horeca", "hospitality", "de"),
        ("betrouwbaar", "reliable", None),
        ("gemotiveerd", "motivated", None),
        ("zelfstandig", "independent", None),
        ("samenwerkend", "collaborative", None),
        ("creatief", "creative", None),
        ("stageschrift", "internship application", "het"),
        ("referentie", "reference", "de"),
        ("aanbeveling", "recommendation", "de"),
        ("sollicitatieformulier", "application form", "het"),
        ("motivatie", "motivation", "de"),
        ("kwalificatie", "qualification", "de"),
        ("vaardigheid", "skill", "de"),
        ("competentie", "competency", "de"),
        ("solliciteren", "to apply", None),
        ("reageren op", "to respond to", None),
        ("uitnodigen voor", "to invite for", None),
        ("afwijzen", "to reject", None),
        ("aannemen", "to hire", None),
        ("proeftijd", "probation period", "de"),
        ("arbeidscontract", "employment contract", "het"),
        ("salaris", "salary", "het"),
        ("secundaire arbeidsvoorwaarden", "benefits", "de"),
        ("pensioen", "pension", "het"),
        ("verlof", "leave", "het"),
        ("kantoor", "office", "het"),
        ("werkplek", "workplace", "de"),
        ("thuiswerken", "to work from home", None),
        ("hybride", "hybrid", None),
        ("netwerk", "network", "het"),
        ("linkedin", "LinkedIn", "de"),
        ("vacaturesite", "job site", "de"),
        ("arbeidsbureau", "employment agency", "het"),
        ("headhunter", "headhunter", "de"),
        ("sollicitatiegesprek voorbereiden", "to prepare for interview", None),
        ("vragen stellen", "to ask questions", None),
        ("onderhandelen", "to negotiate", None),
        ("werkervaring", "work experience", "de"),
        ("bijbaan", "side job", "de"),
    ],
    5: [  # Een dag op het werk - professions, activities, instructions, conditions, schedule
        ("kantoor", "office", "het"),
        ("vergaderzaal", "meeting room", "de"),
        ("koffieautomaat", "coffee machine", "de"),
        ("inloggen", "to log in", None),
        ("uitloggen", "to log out", None),
        ("e-mailen", "to email", None),
        ("faxen", "to fax", None),
        ("archiveren", "to archive", None),
        ("kopiëren", "to copy", None),
        ("scannen", "to scan", None),
        ("opsturen", "to send", None),
        ("doorsturen", "to forward", None),
        ("afdrukken", "to print", None),
        ("opbergen", "to file", None),
        ("overleggen", "to consult", None),
        ("rapporteren", "to report", None),
        ("presenteren", "to present", None),
        ("plannen", "to plan", None),
        ("organiseren", "to organize", None),
        ("delegeeren", "to delegate", None),
        ("controleren", "to check", None),
        ("goedkeuren", "to approve", None),
        ("afkeuren", "to reject", None),
        ("salarisspecificatie", "salary slip", "de"),
        ("loonstrook", "payslip", "de"),
        ("belasting", "tax", "de"),
        ("premie", "premium", "de"),
        ("overuren", "overtime", "de"),
        ("ploegendienst", "shift work", "de"),
        ("ochtenddienst", "morning shift", "de"),
        ("avonddienst", "evening shift", "de"),
        ("nachtdienst", "night shift", "de"),
        ("verlof aanvragen", "to request leave", None),
        ("ziek melden", "to report sick", None),
        ("ziek", "sick", None),
        ("verkouden", "having a cold", None),
        ("griep", "flu", "de"),
        ("ziekmelding", "sick leave", "de"),
        ("arbeidsongeschikt", "disabled", None),
        ("re-integratie", "reintegration", "de"),
        ("functioneringsgesprek", "performance review", "het"),
        ("beoordeling", "assessment", "de"),
        ("kantooruren", "office hours", "de"),
        ("overwerk", "overtime", "het"),
        ("werkdruk", "workload", "de"),
        ("deadline halen", "to meet a deadline", None),
        ("verslag", "report", "het"),
        ("notulen", "minutes", "de"),
        ("actiepunten", "action points", "de"),
        ("afspraak maken", "to make an appointment", None),
        ("nota", "note", "de"),
        ("agenda", "agenda", "de"),
    ],
    6: [  # Officiële instanties - services, driving test, passport, ID
        ("gemeentehuis", "town hall", "het"),
        ("burgerlijke stand", "civil registry", "de"),
        ("uittreksel", "extract", "het"),
        ("geboorteakte", "birth certificate", "de"),
        ("huwelijksakte", "marriage certificate", "de"),
        ("verblijfsvergunning", "residence permit", "de"),
        ("naturalisatie", "naturalization", "de"),
        ("inburgering", "integration", "de"),
        ("inburgeringsexamen", "integration exam", "het"),
        ("rijbewijs halen", "to get a driving licence", None),
        ("rijles", "driving lesson", "de"),
        ("rijinstructeur", "driving instructor", "de"),
        ("theorie-examen", "theory exam", "het"),
        ("praktijkexamen", "practical exam", "het"),
        ("slagen", "to pass", None),
        ("zakken", "to fail", None),
        ("verlengen", "to renew", None),
        ("vervangen", "to replace", None),
        ("duplicaat", "duplicate", "het"),
        ("legitimatie", "identification", "de"),
        ("inschrijven", "to register", None),
        ("uitschrijven", "to deregister", None),
        ("adreswijziging", "change of address", "de"),
        ("digid", "DigiD", "de"),
        ("belastingdienst", "tax office", "de"),
        ("sociale verzekeringsbank", "SVB", "de"),
        ("uitkering", "benefit", "de"),
        ("aow", "state pension", "de"),
        ("bijstand", "welfare", "de"),
        ("kennisgeving", "notification", "de"),
        ("formulier", "form", "het"),
        ("handtekening", "signature", "de"),
        ("stempel", "stamp", "de"),
        ("balie", "counter", "de"),
        ("loket", "window", "het"),
        ("wachtkamer", "waiting room", "de"),
        ("volgnummer", "queue number", "het"),
        ("identiteitsbewijs", "identity document", "het"),
        ("geboortebewijs", "birth certificate", "het"),
        ("verklaring", "declaration", "de"),
        ("legaliseren", "to legalize", None),
        ("apostille", "apostille", "de"),
        ("paspoortkantoor", "passport office", "het"),
        ("rijbewijscentrum", "driving licence centre", "het"),
    ],
    7: [  # Op reis door Nederland - transport, traffic, geography, landscape, trips
        ("trein", "train", "de"),
        ("bus", "bus", "de"),
        ("tram", "tram", "de"),
        ("metro", "metro", "de"),
        ("fiets", "bicycle", "de"),
        ("auto", "car", "de"),
        ("boot", "boat", "de"),
        ("veerpont", "ferry", "de"),
        ("vliegtuig", "airplane", "het"),
        ("station", "station", "het"),
        ("perron", "platform", "het"),
        ("halte", "stop", "de"),
        ("kaartje", "ticket", "het"),
        ("ov-chipkaart", "public transport card", "de"),
        ("inchecken", "to check in", None),
        ("uitchecken", "to check out", None),
        ("overstappen", "to transfer", None),
        ("vertraging", "delay", "de"),
        ("spoor", "track", "het"),
        ("snelweg", "highway", "de"),
        ("verkeerslicht", "traffic light", "het"),
        ("rotonde", "roundabout", "de"),
        ("parkeerplaats", "parking", "de"),
        ("tankstation", "gas station", "het"),
        ("rivier", "river", "de"),
        ("kanaal", "canal", "het"),
        ("meer", "lake", "het"),
        ("polder", "polder", "de"),
        ("dijk", "dyke", "de"),
        ("molen", "windmill", "de"),
        ("strand", "beach", "het"),
        ("duin", "dune", "de"),
        ("bos", "forest", "het"),
        ("weide", "meadow", "de"),
        ("provincie", "province", "de"),
        ("regio", "region", "de"),
        ("bezienswaardigheid", "sight", "de"),
        ("museum", "museum", "het"),
        ("attractie", "attraction", "de"),
        ("uitje", "outing", "het"),
        ("dagje uit", "day trip", "het"),
        ("vakantie", "holiday", "de"),
        ("route", "route", "de"),
        ("navigatie", "navigation", "de"),
        ("file", "traffic jam", "de"),
        ("omleiding", "diversion", "de"),
        ("NS", "Dutch Railways", "de"),
        ("OV", "public transport", "het"),
        ("retour", "return", "de"),
        ("enkele reis", "single journey", "de"),
        ("dagkaart", "day ticket", "de"),
        ("fietsenstalling", "bicycle parking", "de"),
        ("bagage", "luggage", "de"),
        ("koffer", "suitcase", "de"),
        ("haven", "harbour", "de"),
        ("luchthaven", "airport", "de"),
        ("vliegveld", "airport", "het"),
    ],
    8: [  # Geld - money, ATM, prices, pocket money, budget, bank, Tikkie, insurances
        ("euro", "euro", "de"),
        ("cent", "cent", "de"),
        ("biljet", "banknote", "het"),
        ("munt", "coin", "de"),
        ("geldautomaat", "ATM", "de"),
        ("pinnen", "to pay by card", None),
        ("contant", "cash", None),
        ("pinbetaling", "card payment", "de"),
        ("overschrijven", "to transfer", None),
        ("incasso", "direct debit", "de"),
        ("acceptgiro", "giro transfer", "de"),
        ("tikkie", "Tikkie", "het"),
        ("betalingsverzoek", "payment request", "het"),
        ("rekening", "account", "de"),
        ("spaarrekening", "savings account", "de"),
        ("betaalrekening", "current account", "de"),
        ("saldo", "balance", "het"),
        ("rente", "interest", "de"),
        ("hypotheek", "mortgage", "de"),
        ("lening", "loan", "de"),
        ("schuld", "debt", "de"),
        ("sparen", "to save", None),
        ("uitgeven", "to spend", None),
        ("besteden", "to spend", None),
        ("besparen", "to save", None),
        ("budget", "budget", "het"),
        ("uitgaven", "expenses", "de"),
        ("inkomen", "income", "het"),
        ("loon", "wage", "het"),
        ("toeslag", "allowance", "de"),
        ("korting", "discount", "de"),
        ("kassabon", "receipt", "de"),
        ("factuur", "invoice", "de"),
        ("verzekering", "insurance", "de"),
        ("zorgverzekering", "health insurance", "de"),
        ("inboedelverzekering", "contents insurance", "de"),
        ("autoverzekering", "car insurance", "de"),
        ("premie", "premium", "de"),
        ("eigen risico", "excess", "het"),
        ("claim", "claim", "de"),
        ("declareren", "to claim", None),
        ("zakgeld", "pocket money", "het"),
        ("kleedgeld", "clothing allowance", "het"),
        ("pinnen bij", "to withdraw at", None),
        ("opnemen", "to withdraw", None),
        ("storten", "to deposit", None),
        ("automatisch incasso", "direct debit", "de"),
        ("geld opnemen", "to withdraw money", None),
        ("geld storten", "to deposit money", None),
    ],
    9: [  # Geschiedenis - past, Dutch history, life stories, facts
        ("verleden", "past", "het"),
        ("heden", "present", "het"),
        ("toekomst", "future", "de"),
        ("eeuw", "century", "de"),
        ("decennium", "decade", "het"),
        ("generatie", "generation", "de"),
        ("voorouder", "ancestor", "de"),
        ("levensverhaal", "life story", "het"),
        ("herinnering", "memory", "de"),
        ("oorlog", "war", "de"),
        ("bezetting", "occupation", "de"),
        ("bevrijding", "liberation", "de"),
        ("herdenking", "commemoration", "de"),
        ("4 mei", "4 May", None),
        ("5 mei", "5 May", None),
        ("monument", "monument", "het"),
        ("standbeeld", "statue", "het"),
        ("erfgoed", "heritage", "het"),
        ("cultuur", "culture", "de"),
        ("traditie", "tradition", "de"),
        ("folklore", "folklore", "de"),
        ("legende", "legend", "de"),
        ("mythe", "myth", "de"),
        ("feit", "fact", "het"),
        ("weetje", "fact", "het"),
        ("anekdote", "anecdote", "de"),
        ("koning", "king", "de"),
        ("koningin", "queen", "de"),
        ("republiek", "republic", "de"),
        ("kolonie", "colony", "de"),
        ("handel", "trade", "de"),
        ("gouden eeuw", "golden age", "de"),
        ("industriële revolutie", "industrial revolution", "de"),
        ("archief", "archive", "het"),
        ("bron", "source", "de"),
        ("document", "document", "het"),
        ("tentoonstelling", "exhibition", "de"),
        ("rondleiding", "tour", "de"),
        ("gids", "guide", "de"),
        ("historisch", "historical", None),
        ("cultureel", "cultural", None),
        ("erfgoed", "heritage", "het"),
        ("restauratie", "restoration", "de"),
        ("archeologie", "archaeology", "de"),
        ("tijdlijn", "timeline", "de"),
    ],
    10: [  # Samen leven - traditions, festivals, complaining, excusing, social security, faith, politics
        ("traditie", "tradition", "de"),
        ("feestdag", "holiday", "de"),
        ("sinterklaas", "Sinterklaas", "de"),
        ("koningsdag", "King's Day", "de"),
        ("pasen", "Easter", "het"),
        ("kerstmis", "Christmas", "de"),
        ("oud en nieuw", "New Year", "het"),
        ("carnaval", "carnival", "het"),
        ("klacht", "complaint", "de"),
        ("excuses", "apology", "de"),
        ("sorry", "sorry", None),
        ("het spijt me", "I'm sorry", None),
        ("verontschuldiging", "apology", "de"),
        ("bezwaar", "objection", "het"),
        ("reclamatie", "complaint", "de"),
        ("klagen", "to complain", None),
        ("excuseren", "to excuse", None),
        ("verontschuldigen", "to apologize", None),
        ("uitpraten", "to talk out", None),
        ("oplossen", "to resolve", None),
        ("sociale zekerheid", "social security", "de"),
        ("uitkering", "benefit", "de"),
        ("aow", "state pension", "de"),
        ("bijstand", "welfare", "de"),
        ("ww", "unemployment benefit", "de"),
        ("ziektekostenverzekering", "health insurance", "de"),
        ("geloof", "faith", "het"),
        ("religie", "religion", "de"),
        ("kerk", "church", "de"),
        ("moskee", "mosque", "de"),
        ("synagoge", "synagogue", "de"),
        ("politiek", "politics", "de"),
        ("politicus", "politician", "de"),
        ("verkiezing", "election", "de"),
        ("stemmen", "to vote", None),
        ("partij", "party", "de"),
        ("regering", "government", "de"),
        ("parlement", "parliament", "het"),
        ("gezelligheid", "coziness", "de"),
        ("sfeer", "atmosphere", "de"),
        ("mening", "opinion", "de"),
        ("standpunt", "viewpoint", "het"),
        ("argument", "argument", "het"),
        ("discussie", "discussion", "de"),
        ("buurt", "neighborhood", "de"),
        ("buurman", "neighbor", "de"),
        ("buurvrouw", "neighbor", "de"),
        ("vereniging", "association", "de"),
        ("vrijwilliger", "volunteer", "de"),
        ("vrijwilligerswerk", "volunteer work", "het"),
        ("maatschappij", "society", "de"),
        ("integratie", "integration", "de"),
        ("diversiteit", "diversity", "de"),
        ("tolerantie", "tolerance", "de"),
        ("respect", "respect", "het"),
    ],
}


def main():
    with open(WINDMEE_PATH) as f:
        data = json.load(f)

    # Build new vocab: keep existing, add expansions per theme
    existing_by_theme = {}
    for v in data["vocab"]:
        t = v["theme"]
        if t not in existing_by_theme:
            existing_by_theme[t] = []
        existing_by_theme[t].append(v)

    new_vocab = []
    for theme_id in range(1, 11):
        existing = existing_by_theme.get(theme_id, [])
        existing_nl = {v["nl"].lower() for v in existing}

        # Add existing
        for v in existing:
            new_vocab.append(v)

        # Add expansions (skip duplicates)
        if theme_id in EXPANSIONS:
            max_id = max(
                (int(v["id"].split("_")[1]) for v in existing) if existing else -1
            )
            for nl, en, article in EXPANSIONS[theme_id]:
                if nl.lower() not in existing_nl:
                    max_id += 1
                    new_vocab.append({
                        "id": f"w{theme_id:02d}_{max_id:04d}",
                        "theme": theme_id,
                        "nl": nl,
                        "article": article,
                        "en": en,
                        "tags": [],
                    })
                    existing_nl.add(nl.lower())

    # Sort by theme, then id
    new_vocab.sort(key=lambda v: (v["theme"], v["id"]))
    data["vocab"] = new_vocab

    with open(WINDMEE_PATH, "w") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    from collections import Counter
    counts = Counter(v["theme"] for v in data["vocab"])
    print("Wind mee theme counts:")
    for t in sorted(counts.keys()):
        print(f"  Theme {t}: {counts[t]} words")
    print(f"Total: {len(data['vocab'])} words")


if __name__ == "__main__":
    main()
